const searchInput = document.getElementById('searchInput');
const dropdownMenu = document.getElementById('dropdown');
const options = [
    { text: 'Stable Diffusion（SD）3', url: 'https://pan.quark.cn/s/8fc8cf6850d8' },
    { text: 'Stable Diffusion（SD）', url: 'https://pan.quark.cn/s/971c7f41c685' },
    { text: 'SD绘画关键词', url: 'https://pan.quark.cn/s/ba48b90eb11f' },
    { text: 'Krita+ComfyUI', url: 'https://pan.xunlei.com/s/VO0rfhuh-OQUZUEd9q9yovyJA1?pwd=6kmb#' },
    { text: 'Rope-Ruby', url: 'https://pan.xunlei.com/s/VO0rok6pNk5ywysU0X9Nmv5nA1?pwd=qa2h#' },
    { text: 'Print Conductor 批量打印神器', url: 'https://pan.quark.cn/s/6d96a8815a0a' },
    { text: 'Office 批量打印精灵', url: 'https://pan.quark.cn/s/959399b7b83b' },
    { text: 'office 白嫖神器', url: 'https://pan.xunlei.com/s/VOBVpObeG2PCWauNTcs_ha1dA1?pwd=dfy8#' },
    { text: 'Office Installer Plus', url: 'https://pan.xunlei.com/s/VNvrI4QLfz6guXqO8J11KApkA1?pwd=jr2k#' },
    { text: 'Microsoft 365', url: 'https://pan.xunlei.com/s/VNv2qz1HoqTQutMQx_ElsMm8A1?pwd=ra7n#' },
    { text: 'office 2024 精简版', url: 'https://pan.xunlei.com/s/VOEQorAiDOAkeHJQzQaaVBOfA1?pwd=7b25#' },
    { text: 'office 2024 正式版', url: 'https://pan.xunlei.com/s/VO6KeFcPcjLPoTKym9V5q-5qA1?pwd=bk5g#' },
    { text: 'office 2021', url: 'https://pan.xunlei.com/s/VO0ftbZF0fnpk48IhybQbkGkA1?pwd=pm6i#' },
    { text: 'office 2019', url: 'https://pan.xunlei.com/s/VO0ftPXWVBObYuIAV4sE6rXqA1?pwd=7yuy#' },
    { text: 'office 2016', url: 'https://pan.xunlei.com/s/VO0ftWxSFKQvr1ltR5wiI6OeA1?pwd=dfx9#' },
    { text: 'office 2013', url: 'https://pan.xunlei.com/s/VNo1aoKujPszD74r4mLwGfO5A1?pwd=cfc6' },
    { text: 'office 2010', url: 'https://pan.xunlei.com/s/VNx_B_fF2bnRn9BebiEuHIjJA1?pwd=u4pq#' },
    { text: 'office 2007', url: 'https://pan.xunlei.com/s/VNo1b37i0l_fOYP_iNbey5C3A1?pwd=s6nb' },
    { text: 'office 2003', url: 'https://pan.xunlei.com/s/VNo1bA2-1nq1azukZl4XblwzA1?pwd=g4k2' },
    { text: 'office 视频教程', url: 'https://pan.quark.cn/s/0301f1d9734f' },
    { text: 'Excel小白到高手的进阶', url: 'https://pan.xunlei.com/s/VNpXyZ40ZbbbpbQUIqetiR1WA1?pwd=p75k#' },
    { text: 'office全套学习资料', url: 'https://pan.xunlei.com/s/VNpY3TyKE4YypQ2ggSnnNfWmA1?pwd=gfsu#' },
    { text: 'Visio 2024', url: 'https://pan.xunlei.com/s/VO8m2bsjXyk7TKcfDLFZ0E3qA1?pwd=n6a7#' },
    { text: 'Visio 2021', url: 'https://pan.xunlei.com/s/VO0ftpdOXpN_MSIaxAHg_7wIA1?pwd=dq47#' },
    { text: 'Visio 2019', url: 'https://pan.xunlei.com/s/VO0ftuB7vZ1s1WfsI0TRFkciA1?pwd=nigz#' },
    { text: 'Visio 2016', url: 'https://pan.xunlei.com/s/VO0ftyQX2BrOs34d7PEYYs2RA1?pwd=xtds#' },
    { text: 'Visio 2013', url: 'https://pan.xunlei.com/s/VNo1q-3Cn8d5nHT2mwTgjT6eA1?pwd=n24r' },
    { text: 'Visio 2010', url: 'https://pan.xunlei.com/s/VNo1q74kz5fbpiLvCkYk5ju7A1?pwd=xukz' },
    { text: 'Visio 2007', url: 'https://pan.xunlei.com/s/VNo1qGAq9jdW7ZxaKkVX5ODgA1?pwd=u4jp' },
    { text: 'visio视频教程', url: 'https://pan.quark.cn/s/5b152f05c20a' },
    { text: 'Project 2024', url: 'https://pan.xunlei.com/s/VO8m2m6Dvwa3oXzhSu-VQNHrA1?pwd=cgup#' },
    { text: 'Project 2021', url: 'https://pan.xunlei.com/s/VO0fu3g0N_NvId44vnooAp0uA1?pwd=exp8#' },
    { text: 'Project 2019', url: 'https://pan.xunlei.com/s/VO0fu7zAj8KphooNsenMHoFsA1?pwd=9tt8#' },
    { text: 'Project 2016', url: 'https://pan.xunlei.com/s/VO0fuBbsfkKd2c6ZEOYzB2LaA1?pwd=f7ne#' },
    { text: 'Project 2013', url: 'https://pan.xunlei.com/s/VNo1s3j9bDxEyJfwu_VhSfTIA1?pwd=9iy4' },
    { text: 'Project 2010', url: 'https://pan.xunlei.com/s/VNo1sBfQwbqrwdFzLNrLx81FA1?pwd=i9hk' },
    { text: 'Project 2007', url: 'https://pan.xunlei.com/s/VNo1sJg-1BrXRDp3KcfMiweUA1?pwd=8jd9' },
    { text: 'Project视频教程', url: 'https://pan.quark.cn/s/d274a0dd1012' },
    { text: 'WPS 手机版(内置激活码)', url: 'https://pan.quark.cn/s/3d0f12d82ab8' },
    { text: 'WPS PDF专业版', url: 'https://pan.xunlei.com/s/VON_DAx8S9YqasNs3IECwuUfA1?pwd=38ef#' },
    { text: 'WPS 2024（含VBA）', url: 'https://pan.xunlei.com/s/VOCfaP-mAx7ombTiO1V9ro7TA1?pwd=hnxe#' },
    { text: 'WPS 2023专业增强版(含VBA)', url: 'https://pan.xunlei.com/s/VOCfaDZmU4kPvye-v7NvMRvxA1?pwd=bgdy#' },
    { text: 'WPS 2022(内置激活码)', url: 'https://pan.xunlei.com/s/VNy-YFuMGLVYv5ikWyMHEMSgA1?pwd=6mjc#' },
    { text: 'WPS 2021(内置激活码)', url: 'https://pan.xunlei.com/s/VNy-YIzbKTrOaTb2Yb3OsqYWA1?pwd=hx8t#' },
    { text: '福昕PDF 2025', url: 'https://pan.xunlei.com/s/VOOwnkokmpMnVc4_lh0y_fu3A1?pwd=ia9s#' },
    { text: '福昕PDF 2024', url: 'https://pan.xunlei.com/s/VOFFFEW_eWFD_2jLU4nc_oHYA1?pwd=rj8t#' },
    { text: 'Xmind 2025', url: 'https://pan.xunlei.com/s/VOQIH-iTVOSSIrOz2FHXXItGA1?pwd=4uyr#' },
    { text: 'Xmind 2024', url: 'https://pan.xunlei.com/s/VOFFEXVgWjN10iOj4AxeMcfzA1?pwd=6f35#' },
    { text: 'Xmind 2023', url: 'https://pan.xunlei.com/s/VNo2_1KAwbqrwdFzLNrM98CiA1?pwd=8z7i' },
    { text: 'Xmind 2022', url: 'https://pan.xunlei.com/s/VNo2_azpkWI4htKtXyQzpLznA1?pwd=gtrq' },
    { text: 'Xmind 2021', url: 'https://pan.xunlei.com/s/VNo2_iUe-HyngSRUD7OEzYszA1?pwd=qwxz' },
    { text: 'Xmind 2020', url: 'https://pan.xunlei.com/s/VNo2_rFYNCYFTIdFJN53UxGzA1?pwd=brhi' },
    { text: 'Xmind 8', url: 'https://pan.xunlei.com/s/VNo2_zH1IOkdLE_7nUs1k404A1?pwd=5emy' },
    { text: 'SPSS视频教程', url: 'https://pan.quark.cn/s/a3a9c6f85755' },
    { text: 'Origin 2024', url: 'https://pan.xunlei.com/s/VOAMX1wBI4RHNmN5x4mfd-ppA1?pwd=6i83#' },
    { text: 'Origin 2022', url: 'https://pan.xunlei.com/s/VNv2rKLCFRyhSGY7pwhBT9AeA1?pwd=psd8#' },
    { text: 'Origin 2021', url: 'https://pan.xunlei.com/s/VNv2vK_bjdqRfzGgjZME5JZVA1?pwd=b9y2#' },
    { text: 'Origin 2019', url: 'https://pan.xunlei.com/s/VNo6F4eOLWH3wa_PUiq2mgbGA1?pwd=cewy' },
    { text: 'Origin 2018', url: 'https://pan.xunlei.com/s/VNo6FAvXoJyL_PRv1h2Yo6hEA1?pwd=k2j5' },
    { text: 'Origin 2017', url: 'https://pan.xunlei.com/s/VNrA7Y9Ke9VnB2l-oPB5iWh5A1?pwd=pcei#' },
    { text: 'Origin视频教程', url: 'https://pan.quark.cn/s/ff50ea296100' },
    { text: 'Matlab 2024B', url: 'https://pan.xunlei.com/s/VO6l0ECzbr92W59lM--GaPG2A1?pwd=9npg#' },
    { text: 'Matlab 2024A', url: 'https://pan.xunlei.com/s/VO4G2iS3b7yi3DgovT_EXhQ6A1?pwd=9bfh#' },
    { text: 'Matlab 2023B', url: 'https://pan.xunlei.com/s/VNo6GkomhR6CsLIoopEod4SOA1?pwd=vri8' },
    { text: 'Matlab 2023A', url: 'https://pan.xunlei.com/s/VNo6GrtlMLVS4SOd36eSMDshA1?pwd=nsjn' },
    { text: 'Matlab 2022B', url: 'https://pan.xunlei.com/s/VNo6H4V7i7Wtop60ZlxqUHuwA1?pwd=iejy' },
    { text: 'Matlab 2022A', url: 'https://pan.xunlei.com/s/VNo6H8bkseOY77ZMO07ZAAM2A1?pwd=vva8' },
    { text: 'Matlab 2021B', url: 'https://pan.xunlei.com/s/VNo6HEy9zCViEQ2O8_o7gOQ4A1?pwd=hx5x' },
    { text: 'Matlab 2021A', url: 'https://pan.xunlei.com/s/VNo6HJ8U89QzbTdarK8L0b_NA1?pwd=vuzd' },
    { text: 'Matlab 2020B', url: 'https://pan.xunlei.com/s/VNo6HQQpWqvs9ceE_QFzlrxRA1?pwd=igkc' },
    { text: 'Matlab 2020A', url: 'https://pan.xunlei.com/s/VNo6HVOQwbqrwdFzLNrMnD3oA1?pwd=rz2r' },
    { text: 'Matlab 2019B', url: 'https://pan.xunlei.com/s/VNrA6JGJ5hEAwRot7qb0xLfkA1?pwd=d3sf#' },
    { text: 'Matlab 2019A', url: 'https://pan.xunlei.com/s/VNrA6NOpx_OMm-fl9LiJO-qAA1?pwd=6bm8#' },
    { text: 'Matlab 2018B', url: 'https://pan.xunlei.com/s/VNrA6SfIYPeEr0uvig__UW71A1?pwd=g5wd#' },
    { text: 'Matlab 2018A', url: 'https://pan.xunlei.com/s/VNrA6c15NDMcd-r1o-0neB6JA1?pwd=ftt4#' },
    { text: 'Matlab 2017B', url: 'https://pan.xunlei.com/s/VNrA6h5V5hEAwRot7qb0xUAxA1?pwd=yayj#' },
    { text: 'Matlab 2017A', url: 'https://pan.xunlei.com/s/VNrA6lP9D5q5kn8IZWyg2JwVA1?pwd=mpzm#' },
    { text: 'Matlab 2016B', url: 'https://pan.xunlei.com/s/VNrA6pyz2RaPyZzgSGKwJSVPA1?pwd=8jaq#' },
    { text: 'Matlab 2016A', url: 'https://pan.xunlei.com/s/VNrA6u9r42v7UYp4Dc8xDnfyA1?pwd=r5dh#' },
    { text: 'Amos 29', url: 'https://pan.xunlei.com/s/VOL4IkMo0_24zSII9htbsR5TA1?pwd=u3xp#' },
    { text: 'Amos 28', url: 'https://pan.xunlei.com/s/VNqaKrVp7w12JRcdi5ZpvVz_A1?pwd=d7yr#' },
    { text: 'EViews 13', url: 'https://pan.xunlei.com/s/VNqaNLiBGhEPsnFKDHTGp3KUA1?pwd=qthd#' },
    { text: 'Minitab 21', url: 'https://pan.xunlei.com/s/VNqaP50WMYm_Xlp4J0EK7zDiA1?pwd=aqi7#' },
    { text: 'Minitab 20', url: 'https://pan.xunlei.com/s/VNrA5pjh5hEAwRot7qb0x7iJA1?pwd=c5kn#' },
    { text: 'Minitab 19', url: 'https://pan.xunlei.com/s/VNrA5v5N5nvtvp8UOGAUI_-2A1?pwd=s3fp#' },
    { text: 'Minitab 18', url: 'https://pan.xunlei.com/s/VNrA5zFNe9VnB2l-oPB5hxk8A1?pwd=r69y#' },
    { text: 'Minitab 17', url: 'https://pan.xunlei.com/s/VNrA62LLX1Z5myhBpFvyryAdA1?pwd=gkw6#' },
    { text: 'Minitab 16', url: 'https://pan.xunlei.com/s/VNrA66hRpGD74swbLS8ySeR9A1?pwd=8rp8#' },
    { text: 'Stata 18 mac版本', url: 'https://pan.xunlei.com/s/VNqaUvjtYIkFS_o60w6nxk4oA1?pwd=8pyz#' },
    { text: 'Stata 18', url: 'https://pan.xunlei.com/s/VOQ1y-yEP4kF4_0ziQn4LTyZA1?pwd=b6jg#' },
    { text: 'Maple 2023', url: 'https://pan.xunlei.com/s/VNrP-Lj__RA9VonWD8UZv89PA1?pwd=pqi8#' },
    { text: 'Maple 2022', url: 'https://pan.xunlei.com/s/VNrP-WgY_uKgg9hkzwApdOpgA1?pwd=rifq#' },
    { text: 'Maple 2021', url: 'https://pan.xunlei.com/s/VNrP-_GXiSpyHx_xfY_biE6OA1?pwd=syuj#' },
    { text: 'Maple 2020', url: 'https://pan.xunlei.com/s/VNrP-cWPAyb9N7hggKU8Q_U0A1?pwd=ztt8#' },
    { text: 'Maple 2019', url: 'https://pan.xunlei.com/s/VNrP-hri1hMCgOOpSkSm7k8qA1?pwd=ay9d#' },
    { text: 'Maple 2018', url: 'https://pan.xunlei.com/s/VNrP-lOkMNpBBllToro99EjJA1?pwd=dreh#' },
    { text: 'Maple 2017', url: 'https://pan.xunlei.com/s/VNrP-pdvujPl8FFM8LjjAkrIA1?pwd=hj8w#' },
    { text: 'Edraw Max 14', url: 'https://pan.xunlei.com/s/VOFH4U-eyF5B6KsYWx4r3bjpA1?pwd=r335#' },
    { text: 'Edraw Max 13', url: 'https://pan.xunlei.com/s/VNrPxd7VhiW5QbNAVLBNmKTxA1?pwd=8dk7#' },
    { text: 'Edraw Max 12', url: 'https://pan.xunlei.com/s/VNrPxhdWiSpyHx_xfY_by4xQA1?pwd=85gd#' },
    { text: 'Edraw Max 10', url: 'https://pan.xunlei.com/s/VNrPxl0dlzFliqoyzAkuxPiTA1?pwd=6e4r#' },
    { text: 'Edraw Max 9', url: 'https://pan.xunlei.com/s/VNrPxpk9eg_odP_8bPXl5x6nA1?pwd=wsr4#' },
    { text: 'Mplus 8.7', url: 'https://pan.xunlei.com/s/VNrPza36fKxh4k0KGYts2NrgA1?pwd=ejk8#' },
    { text: 'Mplus 8.3', url: 'https://pan.xunlei.com/s/VNrPzeJzjre2MGI3r2vsLoDxA1?pwd=zpus#' },
    { text: 'Mplus 7.4', url: 'https://pan.xunlei.com/s/VNrPzilN0eZfLX9348KyYLsWA1?pwd=4qkw#' },
    { text: 'GeoDa 1.22', url: 'https://pan.xunlei.com/s/VNrQ_kbnHRrfIS2BMJoznA-EA1?pwd=58qb#' },
    { text: 'GeoDa 1.20', url: 'https://pan.xunlei.com/s/VNrQ_oFKs3U6roAJ-oix1w3gA1?pwd=2hs9#' },
    { text: 'GeoDa 1.18', url: 'https://pan.xunlei.com/s/VNrQ_tru8xjH31hZb0BrPuLwA1?pwd=mcdi#' },
    { text: 'GeoDa 1.14', url: 'https://pan.xunlei.com/s/VNrQ_xq1ujPl8FFM8Ljjbmb2A1?pwd=g38b#' },
    { text: 'Cytoscape 3.10', url: 'https://pan.xunlei.com/s/VNrQaZPZ382UjoteUVUnj_-wA1?pwd=htev#' },
    { text: 'Cytoscape 3.9', url: 'https://pan.xunlei.com/s/VNrQadKDs3U6roAJ-oix2_M7A1?pwd=5jk2#' },
    { text: 'Cytoscape 3.8', url: 'https://pan.xunlei.com/s/VNrQahOB_UL3aVlnLdjPxY5_A1?pwd=bdjf#' },
    { text: 'Cytoscape 3.7', url: 'https://pan.xunlei.com/s/VNrQakMMuWJdjRHXwx-i3N0dA1?pwd=xpu5#' },
    { text: 'PDF-XChange 10.0', url: 'https://pan.xunlei.com/s/VNs75V2qc3-XEVxJOqHDMZdbA1?pwd=92d9#' },
    { text: 'PDF-Candy 2.9', url: 'https://pan.xunlei.com/s/VNs75YjNO5z_S_ic8sE02YJeA1?pwd=tdde#' },
    { text: 'Solid Converter 10', url: 'https://pan.xunlei.com/s/VNs75ouEX5K87Fq-Ga2uyTlMA1?pwd=3ua3#' },
    { text: 'CorelDRAW（CDR）Win和Mac版本', url: 'https://pan.xunlei.com/s/VNvIBCE1yizRRjSP30lRl86RA1?pwd=vqtt#' },
    { text: 'Bandizip', url: 'https://pan.xunlei.com/s/VNrsbNZRkUo5yDvYBM5nSSxDA1?pwd=fcmc#' },
    { text: '7-zip', url: 'https://pan.xunlei.com/s/VNrsbbw8i_ANAYl5do__EwyNA1?pwd=8sfp#' },
    { text: 'Autodesk全家桶激活工具及教程', url: 'https://pan.xunlei.com/s/VNobpnESE59Fjsz1fpjXrQU1A1?pwd=zydh#' },
    { text: 'AutoCAD插件包集合', url: 'https://pan.xunlei.com/s/VO0r_95rNk5ywysU0X9NhNMsA1?pwd=nfg2#' },
    { text: 'CAD快速看图', url: 'https://pan.xunlei.com/s/VO1pjJEzmG4drGdXGyUKxGdGA1?pwd=ji99#' },
    { text: 'AutoCAD基础版2026', url: 'https://pan.xunlei.com/s/VOMI2evmaEmC9Kb_8U80X4C3A1?pwd=bvvr#' },
    { text: 'AutoCAD基础版2025', url: 'https://pan.xunlei.com/s/VODG7iQp2cpHv51-wiPIJiE4A1?pwd=qsea#' },
    { text: 'AutoCAD基础版2024', url: 'https://pan.xunlei.com/s/VNtV42mF_8L9n5Entx5XCodkA1?pwd=qt52#' },
    { text: 'AutoCAD基础版2023', url: 'https://pan.quark.cn/s/7e060a6903d1' },
    { text: 'AutoCAD基础版2022', url: 'https://pan.quark.cn/s/b00bc5ca35e6 ' },
    { text: 'AutoCAD基础版2021', url: 'https://pan.quark.cn/s/996b11bdf821' },
    { text: 'AutoCAD基础版2020', url: 'https://pan.xunlei.com/s/VODGyS3aDQVrur8Owrq-1HN6A1?pwd=h287#' },
    { text: 'AutoCAD基础版2019', url: 'https://pan.quark.cn/s/3ddca39dd9c3' },
    { text: 'AutoCAD基础版2018', url: 'https://pan.quark.cn/s/ac73360fd622' },
    { text: 'AutoCAD基础版2017', url: 'https://pan.quark.cn/s/bd0d8e461d87' },
    { text: 'AutoCAD基础版2016', url: 'https://pan.quark.cn/s/30e35f3d8cbe' },
    { text: 'AutoCAD基础版2015', url: 'https://pan.quark.cn/s/2fe78d760be9' },
    { text: 'AutoCAD基础版2014', url: 'https://pan.quark.cn/s/f40a6d705de4' },
    { text: 'AutoCAD基础版2013', url: 'https://pan.quark.cn/s/4188f326bd2c' },
    { text: 'AutoCAD基础版2012', url: 'https://pan.quark.cn/s/27de93697b3b' },
    { text: 'AutoCAD基础版2011', url: 'https://pan.quark.cn/s/3c2866ceeba9' },
    { text: 'AutoCAD基础版2010', url: 'https://pan.quark.cn/s/ee71df4b49d2 ' },
    { text: 'AutoCAD基础版2009', url: 'https://pan.xunlei.com/s/VNrhVN6sA2NqQj_27p2MHNWAA1?pwd=arxp#' },
    { text: 'AutoCAD基础版2008', url: 'https://pan.xunlei.com/s/VNrhVXeOegQygyU-FrNvUdRVA1?pwd=mvej#' },
    { text: 'AutoCAD基础版2007', url: 'https://pan.xunlei.com/s/VNrhVc7Qm2rh7FA0tUrcz3GcA1?pwd=txjv#' },
    { text: 'AutoCAD基础版2006', url: 'https://pan.xunlei.com/s/VNrhVh6vVlUcwyxa0ITM65JNA1?pwd=u5ng#' },
    { text: 'AutoCAD基础版2005', url: 'https://pan.xunlei.com/s/VNrhVlIGFaELj35X2uDB0bqYA1?pwd=iy33#' },
    { text: 'AutoCAD基础版2004', url: 'https://pan.xunlei.com/s/VNrhVq9gZXk0dNphYJqBG_Q7A1?pwd=me9c#' },
    { text: 'CAD视频教程', url: 'https://pan.quark.cn/s/ad1fdc1cac6e' },
    { text: 'AutoCAD精简版2026', url: 'https://pan.xunlei.com/s/VOOwrLCMuj5mYBAuty6GPbbeA1?pwd=g9j8#' },
    { text: 'AutoCAD精简版2025', url: 'https://pan.xunlei.com/s/VNv3-c1K4wHIpQXU-PaQ5IUHA1?pwd=e2rz#' },
    { text: 'AutoCAD精简版2024', url: 'https://pan.xunlei.com/s/VNv3-fThPeQcrufZqxpKQMjtA1?pwd=rhua#' },
    { text: 'AutoCAD精简版2023', url: 'https://pan.xunlei.com/s/VNv3-jaGP4qvpRkYDMK0W5DYA1?pwd=h5fj#' },
    { text: 'AutoCAD精简版2022', url: 'https://pan.xunlei.com/s/VNv3-lxrfn3P_O21nvCsyGHyA1?pwd=j5ti#' },
    { text: 'AutoCAD建筑版2026', url: 'https://pan.xunlei.com/s/VOOMi9Dw46g-d-Ia7ONi5ATQA1?pwd=fcqz#' },
    { text: 'AutoCAD建筑版2025', url: 'https://pan.xunlei.com/s/VO0X3Kf5PVdSuZT1IKax5giDA1?pwd=kbgk#' },
    { text: 'AutoCAD建筑版2024', url: 'https://pan.xunlei.com/s/VNrA4EN9X1Z5myhBpFvyrEywA1?pwd=qddx#' },
    { text: 'AutoCAD建筑版2023', url: 'https://pan.quark.cn/s/e38a0a43b0ea' },
    { text: 'AutoCAD建筑版2022', url: 'https://pan.xunlei.com/s/VNrA4JxZYPeEr0uvig__Tj5AA1?pwd=vp65#' },
    { text: 'AutoCAD建筑版2021', url: 'https://pan.xunlei.com/s/VNrA4NlC2RaPyZzgSGKwIXmwA1?pwd=aiy4#' },
    { text: 'AutoCAD电气版2026', url: 'https://pan.xunlei.com/s/VOMexn1hb0qlKE8avUD0dxSJA1?pwd=ryf8#' },
    { text: 'AutoCAD电气版2025', url: 'https://pan.xunlei.com/s/VO0X3E7CFKQvr1ltR5weYSlNA1?pwd=y3az#' },
    { text: 'AutoCAD电气版2024', url: 'https://pan.xunlei.com/s/VNrA4XSI5hEAwRot7qb0wbGJA1?pwd=6fad#' },
    { text: 'AutoCAD电气版2023', url: 'https://pan.quark.cn/s/638e55a135af' },
    { text: 'AutoCAD电气版2022', url: 'https://pan.xunlei.com/s/VNrA4aSGr0t-PVwVLqZcaDspA1?pwd=t52b#' },
    { text: 'AutoCAD电气版2021', url: 'https://pan.xunlei.com/s/VNrA4eRYD5q5kn8IZWyg1UiCA1?pwd=4n2a#' },
    { text: 'AutoCAD机械版2026', url: 'https://pan.xunlei.com/s/VOMexOnpBoXFkDo8WpWUbxvVA1?pwd=hgfb#' },
    { text: 'AutoCAD机械版2025', url: 'https://pan.xunlei.com/s/VO0X3Qf9N_NvZm9yRJPX5H7hA1?pwd=q7jy#' },
    { text: 'AutoCAD机械版2024', url: 'https://pan.quark.cn/s/25d25f4fc727' },
    { text: 'AutoCAD机械版2023', url: 'https://pan.xunlei.com/s/VNrA4kIf8Uwryk4gFTfQDMNLA1?pwd=uvuf#' },
    { text: 'AutoCAD机械版2022', url: 'https://pan.xunlei.com/s/VNrA4pyMp3Qq5kfcQ2jG2s-ZA1?pwd=5wrd#' },
    { text: 'AutoCAD机械版2021', url: 'https://pan.xunlei.com/s/VNrA4tuZx_OMm-fl9LiJNSW4A1?pwd=ey2x#' },
    { text: '中望CAD 2026', url: 'https://pan.xunlei.com/s/VOOwxvzV1kDaZV5_MpP1aipDA1?pwd=ttxz#' },
    { text: '中望CAD 2025', url: 'https://pan.xunlei.com/s/VO1pj2ICySUPbNC-0eVnunD-A1?pwd=qkin#' },
    { text: '中望CAD 2024', url: 'https://pan.xunlei.com/s/VO-RQ7fW4CF2jSTdY0IXHU-nA1?pwd=t3w3#' },
    { text: '中望CAD 2023', url: 'https://pan.xunlei.com/s/VO-RQD1QW2_1H-9Z0svGBuKbA1?pwd=km9y#' },
    { text: '中望CAD 2021', url: 'https://pan.xunlei.com/s/VO-RQIGl-bNsoImx-BkTrRccA1?pwd=acrz#' },
    { text: '中望CAD 2020', url: 'https://pan.xunlei.com/s/VO-RQLqD5DbYQBu72oxBmVt8A1?pwd=gqyw#' },
    { text: '中望CAD机械版 2024', url: 'https://pan.xunlei.com/s/VO-RQZjbR_lYEFI124IpL12xA1?pwd=ihhs#' },
    { text: '中望CAD机械版 2023', url: 'https://pan.xunlei.com/s/VO-RQarXR9rqkxfI6P6aa9bPA1?pwd=hnku#' },
    { text: '中望CAD建筑版 2024', url: 'https://pan.xunlei.com/s/VO-RQnlMUQttlEef9Zw3WREhA1?pwd=tsqc#' },
    { text: '中望CAD建筑版 2023', url: 'https://pan.xunlei.com/s/VO-RQq4VUQttlEef9Zw3WSC1A1?pwd=7zcb#' },
    { text: '浩辰CAD 2025', url: 'https://pan.xunlei.com/s/VOEdCZLFSU8IGFgxHJt4JAioA1?pwd=xukb#' },
    { text: '浩辰CAD 2024', url: 'https://pan.xunlei.com/s/VO-RTeDlsg6dWzPVPugdpuzgA1?pwd=zjkh#' },
    { text: '浩辰CAD 2023', url: 'https://pan.xunlei.com/s/VO-RThvxJup3U6-i73_I-clWA1?pwd=kmeu#' },
    { text: '浩辰CAD 2022', url: 'https://pan.xunlei.com/s/VO-RTm6kWST_TCWFVCpvGvBeA1?pwd=343d#' },
    { text: '浩辰CAD 2021', url: 'https://pan.xunlei.com/s/VO-RTq50F1Gwd1uHE5BFBOoOA1?pwd=ymv7#' },
    { text: '浩辰CAD 2019', url: 'https://pan.xunlei.com/s/VO-RTuIVGV5BO5isX-Se5BMMA1?pwd=t2km#' },
    { text: 'Civil3D 2026', url: 'https://pan.xunlei.com/s/VOOwsWtfjUEt5HrukX8ALiDXA1?pwd=q5e5#' },
    { text: 'Civil3D 2025', url: 'https://pan.xunlei.com/s/VO0X46tHPVdSuZT1IKax6-ILA1?pwd=vzzq#' },
    { text: 'Civil3D 2024', url: 'https://pan.xunlei.com/s/VO0X4KPaVne-YWfbj2MtYy6vA1?pwd=uf7z#' },
    { text: 'Civil3D 2023', url: 'https://pan.xunlei.com/s/VNrTYdUH_UL3aVlnLdjQqCI8A1?pwd=zpc3#' },
    { text: 'Civil3D 2022', url: 'https://pan.xunlei.com/s/VNo2ZE5OzCViEQ2O8_o71AI-A1?pwd=syza' },
    { text: 'Civil3D 2021', url: 'https://pan.xunlei.com/s/VNo2ZPris3zIwXW9gJUtwI-aA1?pwd=ihhi' },
    { text: 'Civil3D 2020', url: 'https://pan.xunlei.com/s/VNo2ZWp655ZeXzdL87t2cAidA1?pwd=vv9y' },
    { text: 'Maya 2026', url: 'https://pan.xunlei.com/s/VOMpLpcG74LIdBrQwZo8r1XNA1?pwd=7iad#' },
    { text: 'Maya 2025', url: 'https://pan.xunlei.com/s/VNv2w9S3992dyeUIv63XKbu2A1?pwd=3bdn#' },
    { text: 'Maya 2024', url: 'https://pan.xunlei.com/s/VNo2f6qFQXQ7pJ_0gz9SacavA1?pwd=hckm' },
    { text: 'Maya 2023', url: 'https://pan.xunlei.com/s/VNo2fNdO9jdW7ZxaKkVXKUwfA1?pwd=6izx' },
    { text: 'Maya 2022', url: 'https://pan.xunlei.com/s/VNo2fSvv9FzZf47CBthDBu9aA1?pwd=hhsx' },
    { text: 'Maya 2020', url: 'https://pan.xunlei.com/s/VNo2fYiiLWH3wa_PUiq2AmXnA1?pwd=dwre' },
    { text: 'Maya 2019', url: 'https://pan.xunlei.com/s/VNo2fnr33__r9-0mA81lIcXwA1?pwd=xv68' },
    { text: 'Maya 2018', url: 'https://pan.xunlei.com/s/VNo2frnKXdonbUcTnYCdN6-OA1?pwd=v7gk' },
    { text: 'Maya 2017', url: 'https://pan.xunlei.com/s/VNo2fzj3jPszD74r4mLwZVsxA1?pwd=iw46' },
    { text: 'Maya 2016', url: 'https://pan.xunlei.com/s/VNo2g4RDuQjsmR6LqTH1qEJ5A1?pwd=xu9q' },
    { text: 'Maya 2015', url: 'https://pan.xunlei.com/s/VNo2gA5W-HyngSRUD7OF0aNAA1?pwd=vwj7' },
    { text: 'maya视频教程', url: 'https://pan.quark.cn/s/cacc935e3a0f' },
    { text: 'Inventor 2026', url: 'https://pan.xunlei.com/s/VOMffrgBjb4YSTHfIC6nqGL2A1?pwd=msdt#' },
    { text: 'Inventor 2025', url: 'https://pan.xunlei.com/s/VNv2wWzAO6q8nLjfiYx3vjJNA1?pwd=sb35#' },
    { text: 'Inventor 2024', url: 'https://pan.xunlei.com/s/VNo7ZR2B3WQeJoRSsFZfU-aVA1?pwd=sh6q' },
    { text: 'Inventor 2023', url: 'https://pan.xunlei.com/s/VNo7ZgL3zCViEQ2O8_o7z4SUA1?pwd=s37j' },
    { text: 'Inventor 2022', url: 'https://pan.xunlei.com/s/VNo7Zx633WQeJoRSsFZfUA6AA1?pwd=bv24' },
    { text: 'Inventor 2021', url: 'https://pan.xunlei.com/s/VNo7_1_c89QzbTdarK8LJQ4_A1?pwd=tmtg' },
    { text: 'Inventor 2020', url: 'https://pan.xunlei.com/s/VNo7_6_szCViEQ2O8_o7zCB0A1?pwd=w94c' },
    { text: 'Inventor 2019', url: 'https://pan.xunlei.com/s/VNo7_BAjyyhzSlT13cCYY24uA1?pwd=gwau' },
    { text: '天正T30 V1.0', url: 'https://pan.xunlei.com/s/VOLyrnraC7zeh_GB4gPRRHB2A1?pwd=pizp#' },
    { text: '天正T20 V10.0', url: 'https://pan.xunlei.com/s/VNv2wG1j4vTPcm2v3Y5qx_a-A1?pwd=wmva#' },
    { text: '天正T20 V9.0', url: 'https://pan.xunlei.com/s/VNo2brcvQXQ7pJ_0gz9S_bfqA1?pwd=ix9i' },
    { text: '天正T20 V8.0', url: 'https://pan.xunlei.com/s/VNo2cE0y-HyngSRUD7OF-LHTA1?pwd=afc7' },
    { text: '天正T20 V7.0', url: 'https://pan.xunlei.com/s/VNo2cKDwK4FdRof0glCkxYYvA1?pwd=ecni' },
    { text: '天正T20 V6.0', url: 'https://pan.xunlei.com/s/VNo2cPU71nq1azukZl4XszFBA1?pwd=v6nx' },
    { text: 'SketchBook 2022', url: 'https://pan.xunlei.com/s/VNo7XxMk890L2P7eCUhhPEyQA1?pwd=57u6' },
    { text: 'SketchBook 2021', url: 'https://pan.xunlei.com/s/VNo7YFLwwbqrwdFzLNrN4pRDA1?pwd=4ig6' },
    { text: 'SketchBook 2020', url: 'https://pan.xunlei.com/s/VNo7YKmLz5fbpiLvCkYmsXHcA1?pwd=fkpe' },
    { text: 'SketchBook 2019', url: 'https://pan.xunlei.com/s/VNo7YPshSZ1qKc9jfcMsERzIA1?pwd=txc9' },
    { text: 'SketchBook 2018', url: 'https://pan.xunlei.com/s/VNo7YW_UIOkdLE_7nUs2fpRkA1?pwd=y35a' },
    { text: 'Revit 2026', url: 'https://pan.xunlei.com/s/VONSfdfhFqQadzkBYvAKJuR6A1?pwd=u27y#' },
    { text: 'Revit 2025', url: 'https://pan.xunlei.com/s/VNv2wbx9ViPDZJnmTOwAn91zA1?pwd=wnu8#' },
    { text: 'Revit 2024', url: 'https://pan.xunlei.com/s/VNrOtmlNHRrfIS2BMJozJcPTA1?pwd=fvzx#' },
    { text: 'Revit 2023', url: 'https://pan.xunlei.com/s/VNrP9aLq4c5kzaJZkHzrksmpA1?pwd=bdb7#' },
    { text: 'Revit 2022', url: 'https://pan.xunlei.com/s/VNrP9giRDn2_9NzWFP_vvwzuA1?pwd=9tud#' },
    { text: 'Revit 2021', url: 'https://pan.xunlei.com/s/VNrP9kbSwmvXknU8cPk9eBXqA1?pwd=zju6#' },
    { text: 'Revit 2020', url: 'https://pan.xunlei.com/s/VNrP9ofG6E_vieOh5a9AgOz7A1?pwd=ea3q#' },
    { text: 'Revit 2019', url: 'https://pan.xunlei.com/s/VNrP9r30DNDzvYJQ6WPjzX_ZA1?pwd=p89m#' },
    { text: 'Revit 2018', url: 'https://pan.xunlei.com/s/VNrP9wqDMNpBBllToro9CLJBA1?pwd=b9nr#' },
    { text: 'PowerMILL 2025 一键直装版', url: 'https://pan.xunlei.com/s/VNrP9IeF8_RkqS-lqRkaybYCA1?pwd=38sg#' },
    { text: 'PowerMILL 2025', url: 'https://pan.xunlei.com/s/VNrP9IeF8_RkqS-lqRkaybYCA1?pwd=38sg#' },
    { text: 'PowerMILL 2024', url: 'https://pan.xunlei.com/s/VNrP9IeF8_RkqS-lqRkaybYCA1?pwd=38sg#' },
    { text: 'PowerMILL 2023', url: 'https://pan.xunlei.com/s/VNrP9NyBAyb9N7hggKU8Tn2cA1?pwd=c6tc#' },
    { text: 'Navisworks 2024', url: 'https://pan.xunlei.com/s/VNrPBI3ghiW5QbNAVLBN_cTUA1?pwd=wc4r#' },
    { text: 'Navisworks 2023', url: 'https://pan.xunlei.com/s/VNrPBNDHVCqbAaEO8Loxt2vjA1?pwd=iqbc#' },
    { text: 'Moldflow 2024', url: 'https://pan.xunlei.com/s/VNv319XXFRyhSGY7pwhBcdMFA1?pwd=b5n3#' },
    { text: 'Moldflow 2023', url: 'https://pan.xunlei.com/s/VNrQnBwc2xJI7X3S1VqQPWgaA1?pwd=3374#' },
    { text: 'Moldflow 2021', url: 'https://pan.xunlei.com/s/VNrQnTexs3U6roAJ-oixE46cA1?pwd=pja2#' },
    { text: 'Moldflow 2019', url: 'https://pan.xunlei.com/s/VNrQnYMejahERweBq7bwPHgWA1?pwd=guuj#' },
    { text: 'Moldflow 2018', url: 'https://pan.xunlei.com/s/VNrQnbDc6E_vieOh5a9BBPjEA1?pwd=i3hx#' },
    { text: 'adams 2020', url: 'https://pan.xunlei.com/s/VNrhfuzXPTIaXIE1SfqJ7fAqA1?pwd=cpst#' },
    { text: 'Abaqus 2025', url: 'https://pan.xunlei.com/s/VOEoK5rPCJmpsNJPVcjsYCw4A1?pwd=sgts#' },
    { text: 'Abaqus 2024', url: 'https://pan.xunlei.com/s/VNv2zMnVvHZbggN3Sn3D1WwrA1?pwd=fs5f#' },
    { text: 'Abaqus 2023', url: 'https://pan.xunlei.com/s/VNv2zSHVZWCvFS0v75rhk2f7A1?pwd=wyq9#' },
    { text: 'Abaqus 2022', url: 'https://pan.xunlei.com/s/VNv2zVbQavYLQ0erHtRst4cMA1?pwd=spmi#' },
    { text: 'Abaqus 2021', url: 'https://pan.xunlei.com/s/VNv2zYvvdH1sxk35pl3PlcHFA1?pwd=cfua#' },
    { text: 'Abaqus 2020', url: 'https://pan.xunlei.com/s/VNv2zbk5Iq7SW2riEMIZT_szA1?pwd=3kvp#' },
    { text: 'Abaqus 2016', url: 'https://pan.xunlei.com/s/VNv2zeFC_ful0c70H6WGTG5WA1?pwd=bnpb#' },
    { text: 'IntelliJ IDEA 2025', url: 'https://pan.xunlei.com/s/VOODhjNM-N9bxneOpBdUds9hA1?pwd=agh5#' },
    { text: 'IntelliJ IDEA 2024', url: 'https://pan.xunlei.com/s/VOBVr6yTG2PCWauNTcs_id5WA1?pwd=zeh7#' },
    { text: 'IntelliJ IDEA 2023', url: 'https://pan.quark.cn/s/67d81bae6c31' },
    { text: 'IntelliJ IDEA 2022', url: 'https://pan.xunlei.com/s/VNr9y7T4vL8SUVLN2RduOw55A1?pwd=nibu#' },
    { text: 'IntelliJ IDEA 2021', url: 'https://pan.xunlei.com/s/VNr9yB9Rp3Qq5kfcQ2jG-S2SA1?pwd=tbqe#' },
    { text: 'IntelliJ IDEA 2020', url: 'https://pan.xunlei.com/s/VNr9yFqIx_OMm-fl9LiJK6C-A1?pwd=kncn#' },
    { text: 'IntelliJ IDEA 2019', url: 'https://pan.xunlei.com/s/VNr9yK-I5nvt5Phjufuc-3rWA1?pwd=bcp4#' },
    { text: 'IntelliJ IDEA 2018', url: 'https://pan.xunlei.com/s/VNr9yPD04ASlDvG20ze1Es-lA1?pwd=htzm#' },
    { text: 'Java基础入门', url: 'https://pan.xunlei.com/s/VNpXyJ9Xp701SLxZLk01KxwZA1?pwd=bgz5#' },
    { text: 'IntelliJ pyCharm 2025', url: 'https://pan.xunlei.com/s/VOODiFoS1Qf53dyISGnjbfPTA1?pwd=b6zv#' },
    { text: 'IntelliJ pyCharm 2024', url: 'https://pan.xunlei.com/s/VOBVrBTtvgE5V2RJ9bW0i1tYA1?pwd=cj4p#' },
    { text: 'IntelliJ pyCharm 2023', url: 'https://pan.quark.cn/s/05038a1a4ab6' },
    { text: 'Python全能实战小白训练营', url: 'https://pan.xunlei.com/s/VNpTEIYyM0q4ia79biElm9H-A1?pwd=e4dn#' },
    { text: 'IntelliJ webStorm 2024', url: 'https://pan.xunlei.com/s/VOBVrH_UNH0FR2EBs0eqBIj7A1?pwd=tj9y#' },
    { text: 'IntelliJ webStorm 2023', url: 'https://pan.quark.cn/s/dcb70d93e742' },
    { text: 'IntelliJ phpStorm 2025', url: 'https://pan.xunlei.com/s/VOODitw1m2gsNLoFNcOJ1qhoA1?pwd=3qgv#' },
    { text: 'IntelliJ phpStorm 2024', url: 'https://pan.xunlei.com/s/VO4Qi5QhxHazX9u1VNQPkDNTA1?pwd=6z6f#' },
    { text: 'IntelliJ phpStorm 2023', url: 'https://pan.quark.cn/s/2413b27954ae' },
    { text: 'IntelliJ ReSharper 2023', url: 'https://pan.quark.cn/s/a82f60570de5' },
    { text: 'IntelliJ Rider 2025', url: 'https://pan.xunlei.com/s/VOODjFP11Qf53dyISGnjcQ0uA1?pwd=qdfi#' },
    { text: 'IntelliJ Rider 2024', url: 'https://pan.xunlei.com/s/VO4QiRxz4BOA3tG7_bIbv5rzA1?pwd=ig4c#' },
    { text: 'IntelliJ Rider 2023', url: 'https://pan.quark.cn/s/9e1bcfbe7dea' },
    { text: 'IntelliJ CLion 2025', url: 'https://pan.xunlei.com/s/VOODhzp8PTFKi-XwiXs_DwdcA1?pwd=dz9m#' },
    { text: 'IntelliJ CLion 2024', url: 'https://pan.xunlei.com/s/VOBVrLDeV7pdcEHumXy2V8VxA1?pwd=pbfg#' },
    { text: 'IntelliJ CLion 2023', url: 'https://pan.quark.cn/s/77082c832851' },
    { text: 'IntelliJ DataGrip 2025', url: 'https://pan.xunlei.com/s/VOODjSMOCtXWoPwlcQLjVQK_A1?pwd=23qm#' },
    { text: 'IntelliJ DataGrip 2024', url: 'https://pan.xunlei.com/s/VOBVrOYzG2PCWauNTcs_isNzA1?pwd=wagz#' },
    { text: 'IntelliJ DataGrip 2023', url: 'https://pan.quark.cn/s/62c319e3b294' },
    { text: 'IntelliJ GoLand 2025', url: 'https://pan.xunlei.com/s/VOODj2n8twiBsl_VkUsTytEOA1?pwd=4hfb#' },
    { text: 'IntelliJ GoLand 2024', url: 'https://pan.xunlei.com/s/VOBVrRxEamoAfq_9v0mTVowqA1?pwd=63pc#' },
    { text: 'IntelliJ GoLand 2023', url: 'https://pan.quark.cn/s/f5897be83a04' },
    { text: 'IntelliJ ReSharper C++ 2023', url: 'https://pan.quark.cn/s/d618e8a75341' },
    { text: 'SAI2 2024', url: 'https://pan.xunlei.com/s/VOChm6Fr0j__ytQuBxsEYg3OA1?pwd=7h65#' },
    { text: 'SAI2 2023', url: 'https://pan.xunlei.com/s/VNo7G_dluQjsmR6LqTH2eIh1A1?pwd=yzxx' },
    { text: 'SAI2 2022', url: 'https://pan.xunlei.com/s/VNo7GfsuTuj6Lyaf3L5HoCRtA1?pwd=4hah' },
    { text: 'Capture One 23', url: 'https://pan.xunlei.com/s/VNo7SvvvfeZdZbRPoRMdtX2OA1?pwd=aab5' },
    { text: 'Capture One 22', url: 'https://pan.xunlei.com/s/VNo7T0yvRiULyzATZ5QERlanA1?pwd=xkfr' },
    { text: 'Capture One 21', url: 'https://pan.xunlei.com/s/VNo7T6__uw-ei3NV34f_gkEtA1?pwd=mx3f' },
    { text: '万兴喵影', url: 'https://pan.quark.cn/s/e1143c553b12' },
    { text: 'Adobe正版弹窗提示解决方法及卸载工具', url: 'https://pan.quark.cn/s/2c8c87ca790f' },
    { text: 'Adobe 2025全家桶', url: 'https://pan.xunlei.com/s/VOB5rug0hSYdcDgWM9Rabd4zA1?pwd=sqbu#' },
    { text: 'Adobe 2024全家桶', url: 'https://pan.xunlei.com/s/VNqvPYjEjiKYJL6I2T5x1tEZA1?pwd=2b22#' },
    { text: 'Adobe 2023全家桶', url: 'https://pan.quark.cn/s/138467ac99c1' },
    { text: 'Adobe 2022全家桶', url: 'https://pan.xunlei.com/s/VNrA0ieY4ASlDvG20ze1GGVmA1?pwd=8mxf#' },
    { text: 'Adobe 2021全家桶', url: 'https://pan.xunlei.com/s/VNrA0m_x2QOsWr-7uJdRL7yoA1?pwd=8mvt#' },
    { text: 'Adobe 2020全家桶', url: 'https://pan.xunlei.com/s/VNrA0qrCLJHDpCKMnC4wQXmDA1?pwd=tg7y#' },
    { text: 'Adobe 2019全家桶', url: 'https://pan.xunlei.com/s/VNrA0w1mC3DWufWRhvGfj9NgA1?pwd=rjud#' },
    { text: 'Adobe 2018全家桶', url: 'https://pan.xunlei.com/s/VNrA1-8dqGsvO8IvWyPaZql4A1?pwd=sevd#' },
    { text: 'adobe40全家桶激活工具及教程', url: 'https://pan.xunlei.com/s/VNobsChSwBl3UuWkgN6T9-n9A1?pwd=yq27#' },
    { text: 'Photoshop（ps）手机直装版', url: 'https://pan.quark.cn/s/521b23642571' },
    { text: 'Photoshop（ps）mac版本', url: 'https://pan.xunlei.com/s/VNv2sS24NyQ75WfhSX8Ic53aA1?pwd=fer7#' },
    { text: 'Photoshop（ps）插件一键安装板', url: 'https://pan.xunlei.com/s/VNvrIytOp-_r1h9Ud5e6LjSFA1?pwd=4r5f#' },
    { text: '证件照大师插件4.0', url: 'https://pan.xunlei.com/s/VOEQoEpw0TYBcZaP8ZXKtjDKA1?pwd=k82x#' },
    { text: 'Photoshop (Beta)25.11.2675集成ComfyUI', url: 'https://pan.xunlei.com/s/VO1gIVk6LDkQWa53iASuxHpyA1?pwd=wivh#' },
    { text: 'Photoshop（ps）2025集合', url: 'https://pan.xunlei.com/s/VO9jSN6T9xPofLT-PNjzmpyHA1?pwd=k7me#' },
    { text: 'Photoshop（ps）2024 25.11', url: 'https://pan.xunlei.com/s/VO2e8FbjU6fLVr3q7qOLEqAyA1?pwd=mzqv#' },
    { text: 'Photoshop（ps）2024终版', url: 'https://pan.xunlei.com/s/VOCn4xw6MRX4g6LqqHf2klyOA1?pwd=w2xz#' },
    { text: 'Photoshop（ps）2024 25.9.1', url: 'https://pan.xunlei.com/s/VO2YZk6F9t2RuAvHxLknZ6LwA1?pwd=nbme#' },
    { text: 'Photoshop（ps）2024 25.9', url: 'https://pan.xunlei.com/s/VNy_XYeXZ2GgWxPqWCD2T0oqA1?pwd=x59p#' },
    { text: 'Photoshop（ps）2024 25.8', url: 'https://pan.xunlei.com/s/VNvgvx1y6108qG8w-hL3gl2pA1?pwd=629g#' },
    { text: 'Photoshop（ps）2024 25.7', url: 'https://pan.xunlei.com/s/VNxSwTvbHH_JIXzfSWOqH6M4A1?pwd=sx9n#' },
    { text: 'Photoshop（ps）2024 25.6金龙版', url: 'https://pan.xunlei.com/s/VNt1XsKB6-b6S75iVBIX4TraA1?pwd=3kur#' },
    { text: 'Photoshop（ps）2024 25.6金龙版（免安装版）', url: 'https://pan.xunlei.com/s/VNt1XvFnuKawNMFsbSl19XTsA1?pwd=zhqt#' },
    { text: 'Photoshop（ps）2025 神经滤镜', url: 'https://pan.xunlei.com/s/VOAqcjgdm5tPqhOeH5VhIZiSA1?pwd=m7rd#' },
    { text: 'Photoshop（ps）2024 神经滤镜', url: 'https://pan.xunlei.com/s/VNt1XxtmFOY8y3G5Q25ZwmZgA1?pwd=295u#' },
    { text: 'Photoshop（ps）神经滤镜', url: 'https://pan.xunlei.com/s/VNt1XxtmFOY8y3G5Q25ZwmZgA1?pwd=295u#' },
    { text: 'Photoshop（ps）2024', url: 'https://pan.xunlei.com/s/VNtV4537bKFO6WXQ0riFUqqMA1?pwd=36fd#' },
    { text: 'Photoshop（ps）2023', url: 'https://pan.quark.cn/s/f4599a1c6626' },
    { text: 'Photoshop（ps）2022', url: 'https://pan.quark.cn/s/124f058f60c6' },
    { text: 'Photoshop（ps）2021', url: 'https://pan.quark.cn/s/539d9acbf1f9' },
    { text: 'Photoshop（ps）2020', url: 'https://pan.quark.cn/s/adc7be63eea8' },
    { text: 'Photoshop（ps）2019', url: 'https://pan.quark.cn/s/542319b7fd62' },
    { text: 'Photoshop（ps）2018', url: 'https://pan.quark.cn/s/23d9b1c2a207' },
    { text: 'Photoshop（ps）2017', url: 'https://pan.quark.cn/s/5a8dca8af95f' },
    { text: 'Photoshop（ps）CS6', url: 'https://pan.quark.cn/s/d6c76fbf8c17' },
    { text: 'Photoshop（ps）视频教程', url: 'https://pan.quark.cn/s/b117a5f8e523' },
    { text: 'Photoshop（ps）从零基础小白到大神', url: 'https://pan.xunlei.com/s/VNpXzFuxJUNBee3v5M7iLfajA1?pwd=iiw9#' },
    { text: 'Photoshop Elements 2024', url: 'https://pan.xunlei.com/s/VNq5GKQZZuqojpPY2chjvFZOA1?pwd=ct92#' },
    { text: 'Photoshop Elements 2023', url: 'https://pan.xunlei.com/s/VNq5GRcElZgHfssPTWsyjIfhA1?pwd=t2rp#' },
    { text: 'Photoshop Elements 2022', url: 'https://pan.xunlei.com/s/VNq5GVG09jq75Ea01kpUCoWdA1?pwd=qa8j#' },
    { text: 'Photoshop Elements 2021', url: 'https://pan.xunlei.com/s/VNq5GY4JzZt9sWTk5IbYyxkaA1?pwd=59cz#' },
    { text: 'Photoshop Elements 2020', url: 'https://pan.xunlei.com/s/VNq5GawLV5tOoEsI5Z5a5rSiA1?pwd=ncsb#' },
    { text: 'Premiere mac版本', url: 'https://pan.xunlei.com/s/VNv2sm13ILtkqXQYuqYI6JB2A1?pwd=bjwq#' },
    // { text: 'pr 插件一键安装板', url: 'https://pan.xunlei.com/s/VNwm9JGUC5hipr1kfg59jHjSA1?pwd=ekhp#' },
    { text: 'Premiere 2025集合', url: 'https://pan.xunlei.com/s/VO9jT-eSkSJ8-IBPLNDa7jJ9A1?pwd=z2j7#' },
    { text: 'Premiere 2024 24.4.1', url: 'https://pan.xunlei.com/s/VNzKEIqjTZFwhtNgFMYetYjhA1?pwd=7q4j#' },
    { text: 'Premiere 2024', url: 'https://pan.quark.cn/s/8e64341b3ab7' },
    { text: 'Premiere 2023', url: 'https://pan.quark.cn/s/4e6fbee0c052' },
    { text: 'Premiere 2022', url: 'https://pan.quark.cn/s/e11007fd2cd6' },
    { text: 'Premiere 2021', url: 'https://pan.quark.cn/s/0f6c94456d5e' },
    { text: 'Premiere 2020', url: 'https://pan.quark.cn/s/2ec638aad2d8' },
    { text: 'Premiere 2019', url: 'https://pan.quark.cn/s/6cbfe0d57f4f' },
    { text: 'Premiere 2018', url: 'https://pan.quark.cn/s/30e057555c4b' },
    { text: 'Premiere 2017', url: 'https://pan.quark.cn/s/9e3efe4171d7' },
    { text: 'Premiere 视频教程', url: 'https://pan.quark.cn/s/dcdc790536c7' },
    { text: 'Premiere 剪辑指南入行课程', url: 'https://pan.xunlei.com/s/VNpXxr3Uujl-42hkR-OWNMLeA1?pwd=d6nh#' },
    { text: 'Premiere 剪辑指南入行课程', url: 'https://pan.xunlei.com/s/VNpXxr3Uujl-42hkR-OWNMLeA1?pwd=d6nh#' },
    { text: 'AE+Pr高能秘籍课', url: 'https://pan.xunlei.com/s/VNpXxyA_vztfbnFXKGk28rVwA1?pwd=3dcv#' },
    { text: 'PR从零基础入门到视频剪辑大神教程', url: 'https://pan.xunlei.com/s/VNpXzCZkjfZvSvaLQ0VoPFGlA1?pwd=eenh#' },
    { text: 'Premiere Elements 2024', url: 'https://pan.xunlei.com/s/VNq5I0OQkTeKWQHQUBQRjHCgA1?pwd=xfdq#' },
    { text: 'Premiere Elements 2023', url: 'https://pan.xunlei.com/s/VNq5IJ9LMxNlmRiXjOlLHHywA1?pwd=4eg2#' },
    { text: 'Premiere Elements 2022', url: 'https://pan.xunlei.com/s/VNq5IN3lyqSl9wV3Bcf1koOWA1?pwd=8nux#' },
    { text: 'Premiere Elements 2021', url: 'https://pan.xunlei.com/s/VNq5IQYHr4K4HWnNWR7zegd4A1?pwd=qa59#' },
    { text: 'Acrobat 增效工具5.0中文版', url: 'https://pan.quark.cn/s/cb1f1051a3f9' },
    { text: 'Acrobat 2025一键直装版', url: 'https://pan.xunlei.com/s/VOLrwU4zeHq9x3WlceZegquwA1?pwd=yujq#' },
    { text: 'Acrobat 2025', url: 'https://pan.xunlei.com/s/VOKfRhU3lgy34KCC_es0nKJeA1?pwd=iui6#' },
    { text: 'Acrobat 2024 一键安装解锁版', url: 'https://pan.xunlei.com/s/VO3lD7jM8-W4fRuplIMCTKaCA1?pwd=y92x#' },
    { text: 'Acrobat 2024', url: 'https://pan.xunlei.com/s/VNudty76y7mUgXwCAKKdh-aGA1?pwd=mpzc#' },
    { text: 'Acrobat 2023', url: 'https://pan.xunlei.com/s/VOBTbWxEdHV2yJJytpseDCqiA1?pwd=syr5#' },
    { text: 'Acrobat 2022', url: 'https://pan.quark.cn/s/c8385af96b53' },
    { text: 'Acrobat 2021', url: 'https://pan.quark.cn/s/9fff704a0d46' },
    { text: 'Acrobat 2020', url: 'https://pan.quark.cn/s/84776123cde7' },
    { text: 'After Effects（AE）mac版本', url: 'https://pan.xunlei.com/s/VNv2sxSr_ful0c70H6WGRj4GA1?pwd=kcdg#' },
    { text: 'After Effects（AE）2025', url: 'https://pan.xunlei.com/s/VO9w93-b8Ogp-D4lhceRvYadA1?pwd=mfbb#' },
    { text: 'After Effects（AE）2024', url: 'https://pan.quark.cn/s/bebbfc5ec849' },
    { text: 'After Effects（AE）2023', url: 'https://pan.quark.cn/s/65a994f6e7f3' },
    { text: 'After Effects（AE）2022', url: 'https://pan.quark.cn/s/c82fc7d16e3d' },
    { text: 'After Effects（AE）2021', url: 'https://pan.quark.cn/s/ce6ea8fbcfaf' },
    { text: 'After Effects（AE）2020', url: 'https://pan.quark.cn/s/18e479093aec' },
    { text: 'After Effects（AE）2018', url: 'https://pan.quark.cn/s/384465374427' },
    { text: 'After Effects（AE）2017', url: 'https://pan.quark.cn/s/c5e2b79b8bd7' },
    { text: 'After Effects（AE）视频教程', url: 'https://pan.quark.cn/s/50df9e3f4857' },
    { text: 'Animate（AN）mac版本', url: 'https://pan.xunlei.com/s/VNvN0RZQ7WsRmhZv4Jgb6ZXOA1?pwd=ukt6#' },
    { text: 'Animate（AN）2024', url: 'https://pan.quark.cn/s/de5ef2f437f2' },
    { text: 'Animate（AN）2023', url: 'https://pan.quark.cn/s/59d2a8a10c6c' },
    { text: 'Animate（AN）2022', url: 'https://pan.quark.cn/s/34abf3eb109e' },
    { text: 'Animate（AN）2021', url: 'https://pan.quark.cn/s/feafb612ef6a' },
    { text: 'Animate（AN）2020', url: 'https://pan.quark.cn/s/ed76ed27a7ab' },
    { text: 'Animate（AN）2019', url: 'https://pan.quark.cn/s/b47a1e86e793' },
    { text: 'Animate（AN）2018', url: 'https://pan.quark.cn/s/5c779a335334' },
    { text: 'Animate（AN）2017', url: 'https://pan.quark.cn/s/0734474435bc' },
    { text: 'Audition（AU）mac版本', url: 'https://pan.xunlei.com/s/VNv2t5oW_ful0c70H6WGRl04A1?pwd=jtdq#' },
    { text: 'Audition（AU）2025', url: 'https://pan.xunlei.com/s/VO9w9Ua2Dh4ZJ8eSbrVgzeiFA1?pwd=pcrr#' },
    { text: 'Audition（AU）2024', url: 'https://pan.quark.cn/s/5743d2e132d9' },
    { text: 'Audition（AU）2023', url: 'https://pan.quark.cn/s/5c9e8f5d452a' },
    { text: 'Audition（AU）2022', url: 'https://pan.quark.cn/s/a94fa9a997a6' },
    { text: 'Audition（AU）2021', url: 'https://pan.quark.cn/s/aa590c0f7dda' },
    { text: 'Audition（AU）2020', url: 'https://pan.quark.cn/s/a1097c113aca' },
    { text: 'Audition（AU）2019', url: 'https://pan.quark.cn/s/64e2ed31e51a' },
    { text: 'Audition（AU）2018', url: 'https://pan.quark.cn/s/233ea2bc4932' },
    { text: 'Audition（AU）2017', url: 'https://pan.quark.cn/s/5693952597a8' },
    { text: 'Audition（AU）视频教程', url: 'https://pan.quark.cn/s/be5a5561d10e' },
    { text: 'Bridge（AU）mac版本', url: 'https://pan.xunlei.com/s/VNvN0aBQHo_31ZTIr5m5qmcbA1?pwd=v35w#' },
    { text: 'Bridge（AU）2025', url: 'https://pan.xunlei.com/s/VO9jUh-TYvlSeS8z1eAXqLptA1?pwd=3bhn#' },
    { text: 'Bridge（AU）2024', url: 'https://pan.quark.cn/s/fc6a4c4309b6' },
    { text: 'Bridge（AU）2023', url: 'https://pan.xunlei.com/s/VNrA2XQ-x_OMm-fl9LiJME2JA1?pwd=zqtu#' },
    { text: 'Bridge（AU）2022', url: 'https://pan.xunlei.com/s/VNrA2as-NDMcd-r1o-0nceJVA1?pwd=mtvm#' },
    { text: 'Bridge（AU）2021', url: 'https://pan.xunlei.com/s/VNrA2etV4ASlDvG20ze1H09TA1?pwd=g34d#' },
    { text: 'Bridge（AU）2020', url: 'https://pan.xunlei.com/s/VNrA2ijXghJbhICaO3ci4qq_A1?pwd=vej2#' },
    { text: 'Bridge（AU）2019', url: 'https://pan.xunlei.com/s/VNrA2n3rpGD74swbLS8yR-pwA1?pwd=njs3#' },
    { text: 'Bridge（AU）2018', url: 'https://pan.xunlei.com/s/VNrA2r79x_OMm-fl9LiJMNTEA1?pwd=cfdn#' },
    { text: 'Bridge（AU）2017', url: 'https://pan.xunlei.com/s/VNrA2u6X2RaPyZzgSGKwI0VsA1?pwd=t4u4#' },
    { text: 'Dimension 2025', url: 'https://pan.xunlei.com/s/VOR1cZ9IeqlGem2MHranUJoDA1?pwd=t8dv#' },
    { text: 'Dimension 2022', url: 'https://pan.xunlei.com/s/VNrA33SsYPeEr0uvig__TDpiA1?pwd=mf7v#' },
    { text: 'Dimension 2021', url: 'https://pan.quark.cn/s/5b6441e09c24' },
    { text: 'Dimension 2020', url: 'https://pan.xunlei.com/s/VNrA37VgC3DWufWRhvGfjyF6A1?pwd=bgh6#' },
    { text: 'Dimension 2019', url: 'https://pan.xunlei.com/s/VNrA3BLE42v7UYp4Dc8xC8-uA1?pwd=b2en#' },
    { text: 'Dreamweaver 2021', url: 'https://pan.quark.cn/s/5243fe6e7e44' },
    { text: 'Dreamweaver 2020', url: 'https://pan.quark.cn/s/c87dfe750c0e' },
    { text: 'Dreamweaver 2019', url: 'https://pan.quark.cn/s/9a0cccbcd934' },
    { text: 'Dreamweaver 2018', url: 'https://pan.quark.cn/s/1b848f181f8f' },
    { text: 'Dreamweaver 2017', url: 'https://pan.quark.cn/s/68c7029198a6' },
    { text: 'Dreamweaver 视频教程', url: 'https://pan.quark.cn/s/17caf9994154' },
    { text: 'illustrator（AI）mac版本', url: 'https://pan.xunlei.com/s/VNv2tFleWe2duGBSRDnfBNElA1?pwd=4jdj#' },
    { text: 'illustrator（AI）2025', url: 'https://pan.xunlei.com/s/VO9jTVVIxW7F1jZuJZfpMGJVA1?pwd=5frg#' },
    { text: 'illustrator（AI）2024', url: 'https://pan.quark.cn/s/42eea2b2364f' },
    { text: 'illustrator（AI）2023', url: 'https://pan.quark.cn/s/bb586c82d16e' },
    { text: 'illustrator（AI）2022', url: 'https://pan.xunlei.com/s/VOL4GTazfdL-GF2lYui3YPcAA1?pwd=vueu#' },
    { text: 'illustrator（AI）2021', url: 'https://pan.xunlei.com/s/VOL4GXP8KhEoCdLQFyX2jgMPA1?pwd=iugt#' },
    { text: 'illustrator（AI）2020', url: 'https://pan.xunlei.com/s/VOL4Ga9llAyfS0Qbj7r-GRvFA1?pwd=96yz#' },
    { text: 'illustrator（AI）2019', url: 'https://pan.quark.cn/s/dd0ff51bb6c2' },
    { text: 'illustrator（AI）2018', url: 'https://pan.quark.cn/s/83f88d409ce5' },
    { text: 'illustrator（AI）2017', url: 'https://pan.quark.cn/s/adc757ebcdc2' },
    { text: 'illustrator（AI）2015', url: 'https://pan.quark.cn/s/340a7ce2c7f7' },
    { text: 'illustrator（AI）CS6', url: 'https://pan.quark.cn/s/2d4ee0c52634' },
    { text: 'illustrator（AI）CS5', url: 'https://pan.quark.cn/s/7e081956a5ae' },
    { text: 'illustrator（AI）CS5', url: 'https://pan.quark.cn/s/7e081956a5ae' },
    { text: 'illustrator（AI）视频教程', url: 'https://pan.quark.cn/s/ca890b53c1c3' },
    { text: 'InCopy（IC）mac版本', url: 'https://pan.xunlei.com/s/VNvN0oox0_dT43mM0F5fZ3nrA1?pwd=y42c#' },
    { text: 'InCopy（IC）2025', url: 'https://pan.xunlei.com/s/VO9jVny6pO42QYCk1-BiWfdeA1?pwd=eny2#' },
    { text: 'InCopy（IC）2024', url: 'https://pan.quark.cn/s/b251599d9655' },
    { text: 'InCopy（IC）2023', url: 'https://pan.xunlei.com/s/VNrA2-lWtV9EuPjkiovp3WGPA1?pwd=ppie#' },
    { text: 'InCopy（IC）2022', url: 'https://pan.xunlei.com/s/VNrA23qENDMcd-r1o-0ncSXAA1?pwd=zggw#' },
    { text: 'InCopy（IC）2021', url: 'https://pan.xunlei.com/s/VNrA27oCjjWNT9I7jDBp7Q6VA1?pwd=rwzz#' },
    { text: 'InCopy（IC）2020', url: 'https://pan.xunlei.com/s/VNrA2C9EghJbhICaO3ci4dcKA1?pwd=7jsq#' },
    { text: 'InCopy（IC）2019', url: 'https://pan.xunlei.com/s/VNrA2GJGx_OMm-fl9LiJM6ITA1?pwd=a68j#' },
    { text: 'InCopy（IC）2018', url: 'https://pan.xunlei.com/s/VNrA2LrRp3eAVA2V9Cz7M-9aA1?pwd=j4pu#' },
    { text: 'InCopy（IC）2017', url: 'https://pan.xunlei.com/s/VNrA2Q5lvL8SUVLN2RduQuxTA1?pwd=72v7#' },
    { text: 'InDesign（ID）mac版本', url: 'https://pan.xunlei.com/s/VNvN4RiU9P-CiJX9JiixVKggA1?pwd=3k85#' },
    { text: 'InDesign（ID）2025', url: 'https://pan.xunlei.com/s/VOCbGYNbw0PKgLjw4EXUqWqXA1?pwd=v93r#' },
    { text: 'InDesign（ID）2024', url: 'https://pan.quark.cn/s/0a7dee88a8ca' },
    { text: 'InDesign（ID）2023', url: 'https://pan.xunlei.com/s/VNrA1Sgm8Uwryk4gFTfQC3DYA1?pwd=hcac#' },
    { text: 'InDesign（ID）2022', url: 'https://pan.xunlei.com/s/VNrA1WSepGD74swbLS8yQWpGA1?pwd=k24t#' },
    { text: 'InDesign（ID）2021', url: 'https://pan.xunlei.com/s/VNrA1_ivvL8SUVLN2RduQb8zA1?pwd=6s27#' },
    { text: 'InDesign（ID）2020', url: 'https://pan.xunlei.com/s/VNrA1eN7LJHDpCKMnC4wQq_xA1?pwd=2ya6#' },
    { text: 'InDesign（ID）2019', url: 'https://pan.xunlei.com/s/VNrA1j1gjjWNT9I7jDBp76f7A1?pwd=5j2i#' },
    { text: 'InDesign（ID）2018', url: 'https://pan.xunlei.com/s/VNrA1ng7oXh0FhgZXKSMK9MlA1?pwd=m6an#' },
    { text: 'InDesign（ID）2017', url: 'https://pan.xunlei.com/s/VNrA1rgp42v7UYp4Dc8xBUJnA1?pwd=wy6t#' },
    { text: 'Lightroom Classic（LRC）mac版本', url: 'https://pan.xunlei.com/s/VNv2t_5z6PXH7aJ35c7OxQk1A1?pwd=wn5j#' },
    { text: 'Lightroom Classic（LRC）手机版', url: 'https://pan.quark.cn/s/6a0662d41aeb' },
    { text: 'Lightroom Classic（LRC）2025', url: 'https://pan.xunlei.com/s/VO9jU6He6j4KBTQwN7WKdZ_OA1?pwd=ccaf#' },
    { text: 'Lightroom Classic（LRC）2024 13.4', url: 'https://pan.xunlei.com/s/VO2Y_fknSgCaigdmSlv94MkDA1?pwd=zd38#' },
    { text: 'Lightroom Classic（LRC）2024', url: 'https://pan.xunlei.com/s/VNtV4-0FuW16lvT7afc5PxKhA1?pwd=k4yu#' },
    { text: 'Lightroom Classic（LRC）2023', url: 'https://pan.xunlei.com/s/VOL4H0DPXa1hI5KPnNJlWY0OA1?pwd=ceeh#' },
    { text: 'Lightroom Classic（LRC）2022', url: 'https://pan.xunlei.com/s/VOL4H44PVlV7qnhJNd_0mnoYA1?pwd=s6wd#' },
    { text: 'Lightroom Classic（LRC）2021', url: 'https://pan.xunlei.com/s/VOL4H7MTW1Jzlzj2WC-di-agA1?pwd=3zgx#' },
    { text: 'Lightroom Classic（LRC）2020', url: 'https://pan.xunlei.com/s/VOL4HAN6_oOd0tcIGA-vBdGTA1?pwd=uwiw#' },
    { text: 'Lightroom Classic（LRC）2019', url: 'https://pan.xunlei.com/s/VOL4HD3uCDDHc03cO316jvhVA1?pwd=wzm6#' },
    { text: 'Lightroom Classic（LRC）2018', url: 'https://pan.xunlei.com/s/VOL4HFVGDrIUJXR-mAR0dNubA1?pwd=t3cw#' },
    { text: 'Lightroom Classic（LRC）6.4', url: 'https://pan.quark.cn/s/199b8b1809fb' },
    { text: 'Lightroom Classic（LRC）视频教程', url: 'https://pan.quark.cn/s/44c2b6d4fbf4' },
    { text: 'prelude 2022', url: 'https://pan.xunlei.com/s/VNo6I8Oz890L2P7eCUhh7ELYA1?pwd=66ht' },
    { text: 'prelude 2021', url: 'https://pan.xunlei.com/s/VNo6Ic6YSZ1qKc9jfcMrxZIEA1?pwd=5kcu' },
    { text: 'prelude 2020', url: 'https://pan.xunlei.com/s/VNo6IhYcXdonbUcTnYCdzMZxA1?pwd=pir7' },
    { text: 'prelude 2019', url: 'https://pan.xunlei.com/s/VNo6InHAi7Wtop60ZlxqUj3JA1?pwd=xr8j' },
    { text: 'Media Encoder（ME）mac版本', url: 'https://pan.xunlei.com/s/VNvN4f_RR2sKcs1bT85L5DzuA1?pwd=ar8j#' },
    { text: 'Media Encoder（ME）2025', url: 'https://pan.xunlei.com/s/VO9w8ZvRfUpEpq6P8JjPmm3OA1?pwd=ta69#' },
    { text: 'Media Encoder（ME）2024', url: 'https://pan.xunlei.com/s/VNsqpyQLCKu60bdbzIOpTOw1A1?pwd=6ii9#' },
    { text: 'Media Encoder（ME）2023', url: 'https://pan.xunlei.com/s/VNo6MSaOoJyL_PRv1h2YpY-8A1?pwd=6w2z' },
    { text: 'Media Encoder（ME）2022', url: 'https://pan.xunlei.com/s/VNo6MXP3kJGzNnL4bZ3GVaxvA1?pwd=e3n4' },
    { text: 'Media Encoder（ME）2021', url: 'https://pan.xunlei.com/s/VNo6MbJ3z5fbpiLvCkYmFyNdA1?pwd=caff' },
    { text: 'Media Encoder（ME）2020', url: 'https://pan.xunlei.com/s/VNo6MgXBwbqrwdFzLNrMo8yFA1?pwd=rre7' },
    { text: 'Character Animator mac版本', url: 'https://pan.xunlei.com/s/VNvN4p770_dT43mM0F5f_S7NA1?pwd=csyr#' },
    { text: 'Character Animator 2025', url: 'https://pan.xunlei.com/s/VODAioYsWaQ2vOAhq7tgJfx9A1?pwd=rav6#' },
    { text: 'Character Animator 2024', url: 'https://pan.xunlei.com/s/VNo6NWnoyyhzSlT13cCYGVWeA1?pwd=gayx' },
    { text: 'Character Animator 2023', url: 'https://pan.xunlei.com/s/VNo7EBC79jdW7ZxaKkVY98TMA1?pwd=hc5q' },
    { text: 'Character Animator 2022', url: 'https://pan.xunlei.com/s/VNo7EFrRIOkdLE_7nUs2_lyrA1?pwd=ieg8' },
    { text: 'Character Animator 2021', url: 'https://pan.xunlei.com/s/VNo7EMEF3__r9-0mA81m6D1PA1?pwd=h9uk' },
    { text: 'Character Animator 2020', url: 'https://pan.xunlei.com/s/VNo7ESlbWqvs9ceE_QFzyK5LA1?pwd=f6ae' },
    { text: 'Character Animator 2019', url: 'https://pan.xunlei.com/s/VNo7EY84890L2P7eCUhhJUHLA1?pwd=se37' },
    { text: 'Adobe XD 2025', url: 'https://pan.xunlei.com/s/VOR1cnHpX7oNg-Yqx1HEWH1uA1?pwd=ti5j#' },
    { text: 'Adobe XD 55.1', url: 'https://pan.xunlei.com/s/VNqaFGeuFJ9XqL05KHqPo0IcA1?pwd=8xgw#' },
    { text: 'Adobe XD 45.0', url: 'https://pan.xunlei.com/s/VNqaSEPNFJ9XqL05KHqPrVRHA1?pwd=er8c#' },
    { text: 'Adobe XD 22.0', url: 'https://pan.xunlei.com/s/VNqaSJPZyqSl9wV3Bcf8lv4RA1?pwd=sn3w#' },
    { text: 'Navicat （mac版）', url: 'https://pan.xunlei.com/s/VNz8uHztEg84ecxdTDgu8D8GA1?pwd=kz7v#' },
    { text: 'Navicat 17', url: 'https://pan.xunlei.com/s/VNz8uBgIqLk0bKPim9gahF8RA1?pwd=49ds#' },
    { text: 'Navicat 16', url: 'https://pan.xunlei.com/s/VNoVn9XUqGWRaWdqUnA79vZEA1?pwd=dsd5#' },
    { text: 'Oracle数据库工程师入门培训实战', url: 'https://pan.xunlei.com/s/VNpXx2mEyNn3bnwyHtWldtycA1?pwd=xmu7#' },
    { text: 'Oracle数据库工程师入门培训实战', url: 'https://pan.xunlei.com/s/VNpY-oAedAY1sI6FxvdghIvbA1?pwd=65hz#' },
    { text: '6天掌握Mysql基础视频【完整资料】', url: 'https://pan.xunlei.com/s/VNpXx2mEyNn3bnwyHtWldtycA1?pwd=xmu7#' },
    { text: 'keil软件+stm32库', url: 'https://pan.xunlei.com/s/VNv2vmaMdH1sxk35pl3Pkn_QA1?pwd=dxz9#' },
    { text: 'Keil uvision5 C51v957', url: 'https://pan.xunlei.com/s/VNo2Kqxks3zIwXW9gJUtrOm-A1?pwd=a9re' },
    { text: 'Keil uvision5 C51v959', url: 'https://pan.xunlei.com/s/VNo2L7xtUppUNeRsoJ4GQ60BA1?pwd=3j7d' },
    { text: 'Keil uvision5 MDKv518', url: 'https://pan.xunlei.com/s/VNo2LE_heraE43p8mQce_zS3A1?pwd=75j2' },
    { text: 'Visual Studio 2022', url: 'https://pan.xunlei.com/s/VO7RYetURCGxpi__jaHYT54KA1?pwd=97xj#' },
    { text: 'Visual Studio 2019', url: 'https://pan.xunlei.com/s/VNo5d5bqy-RkbRBtxIsRUyPqA1?pwd=qmat' },
    { text: 'Visual Studio 2017', url: 'https://pan.xunlei.com/s/VNo5dBrBWqvs9ceE_QFzcnjDA1?pwd=ixmw' },
    { text: 'Visual Studio 2015', url: 'https://pan.xunlei.com/s/VNo5dHyNWb5ak_Vtm0MIH0x3A1?pwd=z7fb' },
    { text: 'Visual Studio 2013', url: 'https://pan.xunlei.com/s/VNo5dP00jPszD74r4mLx1WmXA1?pwd=ee7r' },
    { text: 'Visual Studio 2012', url: 'https://pan.xunlei.com/s/VNo5dUyHzCViEQ2O8_o7YawwA1?pwd=rihh' },
    { text: 'Visual Studio 2010', url: 'https://pan.xunlei.com/s/VNo5daPQMLVS4SOd36eSDIIwA1?pwd=h8fy' },
    { text: 'Visual Studio Code 2024', url: 'https://pan.xunlei.com/s/VO7RYYVk2UtMJHJ0pUOzp2CDA1?pwd=4w55#' },
    { text: 'Visual Studio Code 2023', url: 'https://pan.xunlei.com/s/VNqaXMCL9jq75Ea01kpjOh83A1?pwd=3bi5#' },
    { text: 'devC++', url: 'https://pan.xunlei.com/s/VO7R_9oMlGmAq1cCOqjxN8ZqA1?pwd=pafx#' },
    { text: '小熊猫DevC++', url: 'https://pan.xunlei.com/s/VO7ReYRNx7c5Fz911nSURhBsA1?pwd=vciy#' },
    { text: 'LabVIEW 2025', url: 'https://pan.xunlei.com/s/VOLMeoKUsq7iZEvjGgYXgRUUA1?pwd=pkmm#' },
    { text: 'LabVIEW 2024', url: 'https://pan.xunlei.com/s/VNy6kDsVHIID7bECYk4nkcqgA1?pwd=w867#' },
    { text: 'LabVIEW 2023', url: 'https://pan.xunlei.com/s/VNo5egm0e6JgMjMm7zY8DJgGA1?pwd=cnfp' },
    { text: 'LabVIEW 2022', url: 'https://pan.xunlei.com/s/VNo5f0Szz5fbpiLvCkYluM3UA1?pwd=rekr' },
    { text: 'LabVIEW 2021', url: 'https://pan.xunlei.com/s/VNo5f5iY6KLR_aL_ViSmSBywA1?pwd=5nx4' },
    { text: 'LabVIEW 2020', url: 'https://pan.xunlei.com/s/VNo5fCYoz5V-wQQxtLntOzKiA1?pwd=timc' },
    { text: 'LabVIEW 2019', url: 'https://pan.xunlei.com/s/VNo5fGVm6BPAu4FFm6_1nyYiA1?pwd=hv2i' },
    { text: 'LabVIEW 2018', url: 'https://pan.xunlei.com/s/VNo5fNYqZeWlPUCprlLns2osA1?pwd=pycd' },
    { text: 'LabVIEW 2017', url: 'https://pan.xunlei.com/s/VNo5fSXvkJGzNnL4bZ3GLly2A1?pwd=gn82' },
    { text: 'SecureCRT8安装包带安装激活视频', url: 'https://pan.xunlei.com/s/VNobuGInmaO9FAJAx_GGI87qA1?pwd=3fyp#' },
    { text: '小白一周学会Linux', url: 'https://pan.xunlei.com/s/VNpY-eTyE4YypQ2ggSnnMDI7A1?pwd=mjxe#' },
    { text: 'Xshell7安装包带安装激活视频', url: 'https://pan.xunlei.com/s/VNoburSD_K0MgPLBisEsLn2XA1?pwd=59aa#' },
    { text: 'Axure RP Pro9.0', url: 'https://pan.xunlei.com/s/VNqaDiCKhQMBWcF_OC5Fb8ICA1?pwd=2vt4#' },
    { text: 'Anaconda 2023', url: 'https://pan.xunlei.com/s/VNqaLzaiBKWiTLFbgJeVzGs7A1?pwd=ywu2#' },
    { text: 'Anaconda 2022', url: 'https://pan.xunlei.com/s/VNrA5MHyx_OMm-fl9LiJNcJEA1?pwd=xfm8#' },
    { text: 'Anaconda 2021', url: 'https://pan.xunlei.com/s/VNrA5QjlX1Z5myhBpFvyrkExA1?pwd=7kvc#' },
    { text: 'Anaconda 2020', url: 'https://pan.xunlei.com/s/VNrA5V80r0t-PVwVLqZcaXX0A1?pwd=mz3x#' },
    { text: 'Anaconda 2019', url: 'https://pan.xunlei.com/s/VNrA5Yt_vL8SUVLN2RduS5PGA1?pwd=rv4s#' },
    { text: 'Anaconda 2018', url: 'https://pan.xunlei.com/s/VNrA5cJAe9VnB2l-oPB5howUA1?pwd=vcty#' },
    { text: 'Android Studio 2022', url: 'https://pan.xunlei.com/s/VNqaMU1EtZV1ucmoAtmBG7M_A1?pwd=r2k5#' },
    { text: 'Typora 1.10.8', url: 'https://pan.xunlei.com/s/VONSf5lUM8w5fKDwGby5F8nzA1?pwd=bghe#' },
    { text: 'Typora 1.9.5', url: 'https://pan.xunlei.com/s/VOF7fNyzDVW4VmamywnbO0p0A1?pwd=u4ch#' },
    { text: 'Typora 1.9.4', url: 'https://pan.xunlei.com/s/VO0X1mwtFKQvr1ltR5weXtkmA1?pwd=mrdy#' },
    { text: 'Typora 1.9.3', url: 'https://pan.xunlei.com/s/VO0X1rSv2BrOulXaefC3GZgCA1?pwd=kcb3#' },
    { text: 'typora 1.8.5', url: 'https://pan.xunlei.com/s/VNrQbB0tDNDzvYJQ6WPkP8WoA1?pwd=xda7#' },
    { text: 'typora 1.7.6', url: 'https://pan.xunlei.com/s/VNrPwcD0uWJdjRHXwx-hqqfLA1?pwd=xxuq#' },
    { text: 'typora 1.6.5', url: 'https://pan.xunlei.com/s/VNrPwjg5eg_odP_8bPXl5ffLA1?pwd=mafz#' },
    { text: 'typora 1.5.6', url: 'https://pan.xunlei.com/s/VNrPwoEHDNDzvYJQ6WPkB5zBA1?pwd=m9u3#' },
    { text: 'CINEMA 4D（C4D）2025带Redshift渲染器', url: 'https://pan.xunlei.com/s/VOEoKdMTG181uFd_XPpoyosEA1?pwd=nvvm#' },
    { text: 'CINEMA 4D（C4D）2025', url: 'https://pan.xunlei.com/s/VO6kzIvTbQ3fi__q9e_SQn2SA1?pwd=sbrc#' },
    { text: 'CINEMA 4D（C4D）2024.5.0', url: 'https://pan.xunlei.com/s/VO2T68ssXgyxwKqfN8PG7xw8A1?pwd=cp9g#' },
    { text: 'CINEMA 4D（C4D）2024', url: 'https://pan.xunlei.com/s/VNqa7oeth2Dk2j6izHdevBKZA1?pwd=p62g#' },
    { text: 'CINEMA 4D（C4D）2023', url: 'https://pan.xunlei.com/s/VNo2-n7gWqvs9ceE_QFyxMlIA1?pwd=v5ht' },
    { text: 'CINEMA 4D（C4D）S26', url: 'https://pan.xunlei.com/s/VNo20L1k0l_fOYP_iNbf2hUaA1?pwd=2krg' },
    { text: 'CINEMA 4D（C4D）R25', url: 'https://pan.xunlei.com/s/VNo20cVDLWH3wa_PUiq1zGpwA1?pwd=fmwc' },
    { text: 'CINEMA 4D（C4D）S24', url: 'https://pan.xunlei.com/s/VNo20kFghR6CsLIoopEnp0uJA1?pwd=t593' },
    { text: 'CINEMA 4D（C4D）S23', url: 'https://pan.xunlei.com/s/VNo20qhjMLVS4SOd36eRYC5VA1?pwd=ntsb' },
    { text: 'CINEMA 4D（C4D）S22', url: 'https://pan.xunlei.com/s/VNo20zW1seOY77ZMO07YMH_WA1?pwd=zc47' },
    { text: 'CINEMA 4D（C4D）S21', url: 'https://pan.xunlei.com/s/VNo214ysoIJH9sq4VQ8A1t6JA1?pwd=4vpm' },
    { text: 'CINEMA 4D（C4D）S20', url: 'https://pan.xunlei.com/s/VNo21BCst3eLKoEmwXEYnJJhA1?pwd=ign5' },
    { text: 'CINEMA 4D（C4D）S18', url: 'https://pan.xunlei.com/s/VNo21Fr4sZg6p7d4AR1Hx00pA1?pwd=cuzf' },
    { text: 'CINEMA 4D（C4D）视频教程', url: 'https://pan.quark.cn/s/e2c22977f4b1' },
    { text: '3D Studio Max（3ds Max）2026', url: 'https://pan.xunlei.com/s/VOMevl4z_vC1xtLDN7rYcRFWA1?pwd=p6wn#' },
    { text: '3D Studio Max（3ds Max）2025', url: 'https://pan.xunlei.com/s/VNudtv_Du7HmrImYf-QpVSSOA1?pwd=9cg2#' },
    { text: '3D Studio Max（3ds Max）2024', url: 'https://pan.xunlei.com/s/VNo2IKdmuQjsmR6LqTH1iHYQA1?pwd=jspn' },
    { text: '3D Studio Max（3ds Max）2023', url: 'https://pan.xunlei.com/s/VNo2Ja3vn8d5nHT2mwTgrLl1A1?pwd=q926' },
    { text: '3D Studio Max（3ds Max）2022', url: 'https://pan.xunlei.com/s/VNo2JgUas3zIwXW9gJUtr0q4A1?pwd=u7ei' },
    { text: '3D Studio Max（3ds Max）2021', url: 'https://pan.xunlei.com/s/VNo2JmlmkJGzNnL4bZ3Fl6XdA1?pwd=mauh' },
    { text: '3D Studio Max（3ds Max）2020', url: 'https://pan.xunlei.com/s/VNo2Js12MLVS4SOd36eRcb65A1?pwd=tkei' },
    { text: '3D Studio Max（3ds Max）2019', url: 'https://pan.xunlei.com/s/VNo2JyaKe6JgMjMm7zY7bofrA1?pwd=zuh9' },
    { text: '3D Studio Max（3ds Max）2018', url: 'https://pan.xunlei.com/s/VNo2K5mG9FzZf47CBthD4M5ZA1?pwd=nxds' },
    { text: '3D Studio Max（3ds Max）2017', url: 'https://pan.xunlei.com/s/VNo2KCPkuMiCaTDG2_FkJVs0A1?pwd=jy3m' },
    { text: '3D Studio Max（3ds Max）2016', url: 'https://pan.xunlei.com/s/VNo2KIGc1BrXRDp3KcfMqMxRA1?pwd=4xnc' },
    { text: '3D Studio Max（3ds Max）2015', url: 'https://pan.xunlei.com/s/VNo2KN1x1nq1azukZl4Xmd2KA1?pwd=h2qx' },
    { text: '3D Studio Max（3ds Max）2014', url: 'https://pan.xunlei.com/s/VNo2KU80wYPUTOXGEbjUCM76A1?pwd=myjf' },
    { text: '3D Studio Max（3ds Max）教程', url: 'https://pan.quark.cn/s/90acfb3e417a' },
    { text: 'SketchUp（SU）2025', url: 'https://pan.xunlei.com/s/VOK6dY7oA68rv99MmQBHgXDHA1?pwd=un3i#' },
    { text: 'SketchUp（SU）2024', url: 'https://pan.xunlei.com/s/VNv3-vm9rRwqqxbivr4ZYsEQA1?pwd=3vf5#' },
    { text: 'SketchUp（SU）2023', url: 'https://pan.xunlei.com/s/VNo2dE3f3__r9-0mA81lHn9oA1?pwd=xkxt' },
    { text: 'SketchUp（SU）2022', url: 'https://pan.xunlei.com/s/VNo2dSg2wbqrwdFzLNrMAg_iA1?pwd=9iye' },
    { text: 'SketchUp（SU）2021', url: 'https://pan.xunlei.com/s/VNo2d_fi890L2P7eCUhgV6pGA1?pwd=9m8r' },
    { text: 'SketchUp（SU）2020', url: 'https://pan.xunlei.com/s/VNo2dgM26BPAu4FFm6_1JsvCA1?pwd=xn2c' },
    { text: 'SketchUp（SU）2019', url: 'https://pan.xunlei.com/s/VNo2dmny97kTBWzQWgZWgSPTA1?pwd=rhpv' },
    { text: 'SketchUp（SU）2018', url: 'https://pan.xunlei.com/s/VNo2dsHcoJyL_PRv1h2YBcxWA1?pwd=dkc3' },
    { text: 'SketchUp（SU）教程', url: 'https://pan.quark.cn/s/d5eb5fdd856a' },
    { text: 'SolidWorks（SW）2025集合', url: 'https://pan.xunlei.com/s/VOC3dpEJ44i4tgGF_BK_2KZnA1?pwd=ckfu#' },
    { text: 'SolidWorks（SW）2024SP5.0', url: 'https://pan.xunlei.com/s/VOA_WUoIVFzs56Arorr0tRi1A1?pwd=9iph#' },
    { text: 'SolidWorks（SW）2024SP4.0', url: 'https://pan.xunlei.com/s/VO90U_rFtyTZMAkBpf2Yc98PA1?pwd=a738#' },
    { text: 'SolidWorks（SW）2024SP3.1', url: 'https://pan.xunlei.com/s/VO1uaCssUHOkfY8g1rLluuXPA1?pwd=bs9y#' },
    { text: 'SolidWorks（SW）2024', url: 'https://pan.xunlei.com/s/VNrA3djDNDMcd-r1o-0nd1sdA1?pwd=ydcb#' },
    { text: 'SolidWorks（SW）2023', url: 'https://pan.xunlei.com/s/VNo2iUBloIJH9sq4VQ8AGCKRA1?pwd=3cni' },
    { text: 'SolidWorks（SW）2022', url: 'https://pan.xunlei.com/s/VNo2id_2Dfjgkx4DmSC3zgXrA1?pwd=8yup' },
    { text: 'SolidWorks（SW）2021', url: 'https://pan.xunlei.com/s/VNo2ijn4QXQ7pJ_0gz9SboQjA1?pwd=vcxa' },
    { text: 'SolidWorks（SW）2020', url: 'https://pan.xunlei.com/s/VNo2j5ooz5V-wQQxtLnswkTPA1?pwd=8dk7' },
    { text: 'SolidWorks（SW）2019', url: 'https://pan.xunlei.com/s/VNo2jCeRuMiCaTDG2_FkS0ShA1?pwd=s5nw' },
    { text: 'SolidWorks（SW）2018', url: 'https://pan.xunlei.com/s/VNo2jHRHs3zIwXW9gJUtztNZA1?pwd=bvix' },
    { text: 'UG NX 2412', url: 'https://pan.xunlei.com/s/VOL4I1N1CDDHc03cO316kNZoA1?pwd=wfic#' },
    { text: 'UG NX 2406', url: 'https://pan.xunlei.com/s/VO-_J6rOqCCZeGXZfhSRfmTnA1?pwd=qmkt#' },
    { text: 'UG NX 2406 免安装版', url: 'https://pan.quark.cn/s/ca7383abf76e' },
    { text: 'UG NX 2312', url: 'https://pan.xunlei.com/s/VO-RGFlmJup3U6-i73_HtsF2A1?pwd=hyfs#' },
    { text: 'UG NX 2312 免安装版', url: 'https://pan.quark.cn/s/b42adbed5324' },
    { text: 'UG NX 12', url: 'https://pan.xunlei.com/s/VNo2keJXl3alvtQOUozrvRxiA1?pwd=r267' },
    { text: 'UG NX 12 免安装版', url: 'https://pan.xunlei.com/s/VO45s5rLH6DE5lEe_mo5SyQIA1?pwd=h9ds#' },
    { text: 'UG NX 11', url: 'https://pan.xunlei.com/s/VNo2klFRwV_GpXrL7RdTj3XRA1?pwd=n6ik' },
    { text: 'UG NX 10', url: 'https://pan.xunlei.com/s/VNo2kqyfSZ1qKc9jfcMrMNSSA1?pwd=innb' },
    { text: 'UG NX 10 免安装版', url: 'https://pan.quark.cn/s/8e69d01b30e3' },
    { text: 'UG NX 9', url: 'https://pan.xunlei.com/s/VNo2kwLxiRSY3D8mjG_bxOlhA1?pwd=xxji' },
    { text: 'UG NX 8', url: 'https://pan.xunlei.com/s/VNo2qeGXMLVS4SOd36eRnXM-A1?pwd=e886' },
    { text: 'Rhino 8.1', url: 'https://pan.xunlei.com/s/VNo7HT1Ec7M9D1JIPU7fze70A1?pwd=qq8z' },
    { text: 'Rhino 7.33', url: 'https://pan.xunlei.com/s/VNo7I5gpoJyL_PRv1h2Z0xWjA1?pwd=a4tz' },
    { text: 'Rhino 7.30', url: 'https://pan.xunlei.com/s/VNo7IESp9jdW7ZxaKkVYAEBiA1?pwd=5hht' },
    { text: 'Rhino 7.29', url: 'https://pan.xunlei.com/s/VNo7IJRN6KLR_aL_ViSmnxAKA1?pwd=mzch' },
    { text: 'Rhino 7.26', url: 'https://pan.xunlei.com/s/VNo7IRqeWqvs9ceE_QFzzOtsA1?pwd=vbhs' },
    { text: 'Mastercam 2025', url: 'https://pan.xunlei.com/s/VNv2wPSPtR-R-Zoc41Q1p8mzA1?pwd=jknx#' },
    { text: 'Mastercam 2024', url: 'https://pan.xunlei.com/s/VNo7JzozwV_GpXrL7RdVgysoA1?pwd=vknq' },
    { text: 'Mastercam 2023', url: 'https://pan.xunlei.com/s/VNo7KJFASZ1qKc9jfcMsAD-fA1?pwd=3xes' },
    { text: 'Mastercam 2022', url: 'https://pan.xunlei.com/s/VNo7KPOCK4FdRof0glClo0mRA1?pwd=jmru' },
    { text: 'Mastercam 2021', url: 'https://pan.xunlei.com/s/VNo7KVT0Wqvs9ceE_QFzzxeRA1?pwd=4b2c' },
    { text: 'Mastercam 2020', url: 'https://pan.xunlei.com/s/VNo7KaKJDfjgkx4DmSC4oOuUA1?pwd=bjra' },
    { text: 'Mastercam X9', url: 'https://pan.xunlei.com/s/VNo7KeYg6jonMWl9XffZrBaUA1?pwd=bszc' },
    { text: 'Blender 4.2', url: 'https://pan.xunlei.com/s/VO90T_3Pb_qQgtUmQ798E9CEA1?pwd=uqef#' },
    { text: 'Blender 4.0', url: 'https://pan.xunlei.com/s/VNo7TdL3z5fbpiLvCkYmorbXA1?pwd=cwx4' },
    { text: 'Blender 3.5', url: 'https://pan.xunlei.com/s/VNo7TwN3XdonbUcTnYCeF-ccA1?pwd=h6fi' },
    { text: 'Blender 3.3', url: 'https://pan.xunlei.com/s/VNo7U2Gc0l_fOYP_iNbg8FzHA1?pwd=dkem' },
    { text: 'Blender 3.0', url: 'https://pan.xunlei.com/s/VNo7U8KaXdonbUcTnYCeF4H2A1?pwd=wbgn' },
    { text: 'CATIA Composer 2024', url: 'https://pan.xunlei.com/s/VNrhd_kVZXk0dNphYJqBHvRmA1?pwd=vfq7#' },
    { text: 'Catia P3 V5-6R 2020', url: 'https://pan.xunlei.com/s/VO3lCcftg0OtKUo8KFP39GfhA1?pwd=bmr2#' },
    { text: 'Creo 11', url: 'https://pan.xunlei.com/s/VNx_e1bQjE3V6l_36sRfmzm8A1?pwd=vkd4#' },
    { text: 'Creo 10', url: 'https://pan.xunlei.com/s/VNs75JJoKmBZXpffJiQsBdTNA1?pwd=ca5i#' },
    { text: 'Creo 9', url: 'https://pan.xunlei.com/s/VNv2zuZRN5ahD_-qxZ2r4IBhA1?pwd=dk4q#' },
    { text: 'Creo 8', url: 'https://pan.xunlei.com/s/VNv2zy2lvHZbggN3Sn3D1cgKA1?pwd=5ium#' },
    { text: 'Creo 7', url: 'https://pan.xunlei.com/s/VNv3-0g_3KF0Ir94-IdLyozCA1?pwd=x5kv#' },
    { text: 'Creo 6', url: 'https://pan.xunlei.com/s/VNv3-7Z2oqTQutMQx_Elub7rA1?pwd=7fkx#' },
    { text: 'Creo 5', url: 'https://pan.xunlei.com/s/VNv3-BQatR-R-Zoc41Q1pvioA1?pwd=8qxz#' },
    { text: 'Cubase 13', url: 'https://pan.xunlei.com/s/VNo7M-z9UppUNeRsoJ4HNKgEA1?pwd=xxbr' },
    { text: 'Cubase 12', url: 'https://pan.xunlei.com/s/VNo7M5T_0l_fOYP_iNbg5tHFA1?pwd=bdaq' },
    { text: 'Cubase 11', url: 'https://pan.xunlei.com/s/VNo7MAfi-HyngSRUD7OFrcoyA1?pwd=rpg5' },
    { text: 'Cubase 9', url: 'https://pan.xunlei.com/s/VNo7RTxQWqvs9ceE_QG-0zJBA1?pwd=cs6x' },
    { text: 'ACDSee 2025', url: 'https://pan.xunlei.com/s/VO90ULfnb_qQgtUmQ798Eg1tA1?pwd=iiei#' },
    { text: 'ACDSee 2024', url: 'https://pan.xunlei.com/s/VNo7Ue28RiULyzATZ5QESL8AA1?pwd=xp9n' },
    { text: 'ACDSee 2023', url: 'https://pan.xunlei.com/s/VNo7Ux8Y97kTBWzQWgZX_KEBA1?pwd=tjpq' },
    { text: 'ACDSee 2022', url: 'https://pan.xunlei.com/s/VNo7V1sHp1hn07Iy9R1vgwjYA1?pwd=kzi8' },
    { text: 'ACDSee 2021', url: 'https://pan.xunlei.com/s/VNo7V8X3RiULyzATZ5QESUabA1?pwd=rgvw' },
    { text: 'ACDSee 2020', url: 'https://pan.xunlei.com/s/VNo7VDj7oIJH9sq4VQ8B6zz1A1?pwd=dseg' },
    { text: 'Corel Painter 2023', url: 'https://pan.xunlei.com/s/VNo7VoR2l3alvtQOUozsn9LyA1?pwd=uz4z' },
    { text: 'Corel Painter 2022', url: 'https://pan.xunlei.com/s/VNo7W2JD3WQeJoRSsFZfSxNtA1?pwd=4tev' },
    { text: 'Corel Painter 2021', url: 'https://pan.xunlei.com/s/VNo7W7q_Wb5ak_Vtm0MIgGrJA1?pwd=kan2' },
    { text: 'Corel Painter 2020', url: 'https://pan.xunlei.com/s/VNo7WDRoLWH3wa_PUiq33jnEA1?pwd=ynsy' },
    { text: 'Corel Painter 2019', url: 'https://pan.xunlei.com/s/VNo7WJXj55ZeXzdL87t3YInbA1?pwd=5r3b' },
    { text: 'EDIUS 9.0', url: 'https://pan.xunlei.com/s/VNo7WxW2Dfjgkx4DmSC4s7dPA1?pwd=8rfv' },
    { text: 'EDIUS 8.5', url: 'https://pan.xunlei.com/s/VNo7XLQ1UppUNeRsoJ4HQnXmA1?pwd=n3in' },
    { text: 'EDIUS 6.5', url: 'https://pan.xunlei.com/s/VNo7XQaXMLVS4SOd36eSdHf7A1?pwd=ebwr' },
    { text: '达芬奇17.4.6 mac版', url: 'https://pan.xunlei.com/s/VNywuaNi7IbTJWjuiZdA5CJ-A1?pwd=u39t#' },
    { text: '达芬奇20版本集合', url: 'https://pan.xunlei.com/s/VONSelEwRjqUXfoQ4YKkE6SeA1?pwd=b27h#' },
    { text: '达芬奇19.1.4 直装版', url: 'https://pan.xunlei.com/s/VOMCnvDGwAEOuFjUkKzuQs2jA1?pwd=dw8w#' },
    { text: '达芬奇19.1.3 直装版', url: 'https://pan.xunlei.com/s/VOIpCVtnWo_Ebo9LSQZywBkUA1?pwd=9md9#' },
    { text: '达芬奇19.1.2.3', url: 'https://pan.xunlei.com/s/VOEdDFMxvB4s18bM2TssRn1TA1?pwd=t64g#' },
    { text: '达芬奇19.1.1.8直装版（安装即永久激活）', url: 'https://pan.xunlei.com/s/VODlE1HuGz-dTukKwyumigkUA1?pwd=8xxk#' },
    { text: '达芬奇 19', url: 'https://pan.xunlei.com/s/VNvbiVDmHD00qncnjcMKKI6kA1?pwd=y27s#' },
    { text: '达芬奇 18.6.6', url: 'https://pan.xunlei.com/s/VO4BGZa6OUsFN18FXXb226lNA1?pwd=epnf#' },
    { text: '达芬奇 18.6.3', url: 'https://pan.xunlei.com/s/VNuNPHiw_4atcXK51_QbvZc_A1?pwd=p9a2#' },
    { text: '达芬奇 18.5', url: 'https://pan.xunlei.com/s/VNo7bMtaMLVS4SOd36eSerVuA1?pwd=8394' },
    { text: '达芬奇 18.0', url: 'https://pan.xunlei.com/s/VNo7bRtxs3zIwXW9gJUuuRlFA1?pwd=nhei' },
    { text: '达芬奇 17.4', url: 'https://pan.xunlei.com/s/VNo7bYrhQXQ7pJ_0gz9TXFMRA1?pwd=gb87' },
    { text: '达芬奇 17.2', url: 'https://pan.xunlei.com/s/VNo7bcqbTuj6Lyaf3L5Huyj3A1?pwd=4gbz' },
    { text: '达芬奇 16.2', url: 'https://pan.xunlei.com/s/VNo7bhczc7M9D1JIPU7g5MmpA1?pwd=g98m' },
    { text: '达芬奇 15.3', url: 'https://pan.xunlei.com/s/VNo7bnh0p1hn07Iy9R1vjV16A1?pwd=gfsr' },
    { text: '达芬奇 14.3', url: 'https://pan.xunlei.com/s/VNo7bsMMTuj6Lyaf3L5Hv3TRA1?pwd=4ey7' },
    { text: '达芬奇 视频教程', url: 'https://pan.quark.cn/s/ee504c8f2811' },
    { text: 'Global Mapper 25', url: 'https://pan.xunlei.com/s/VNrP0XOPujPl8FFM8LjjAwAjA1?pwd=x7tp#' },
    { text: 'Global Mapper 24', url: 'https://pan.xunlei.com/s/VNrP0b79382UjoteUVUnH3JxA1?pwd=gwfr#' },
    { text: 'Global Mapper 23', url: 'https://pan.xunlei.com/s/VNrP0fr2Ayb9N7hggKU8QvhTA1?pwd=ajmf#' },
    { text: 'Global Mapper 22', url: 'https://pan.xunlei.com/s/VNrP0javmKHZd4RHTjKuDFtzA1?pwd=9h3e#' },
    { text: 'ArcGIS Pro 3.3', url: 'https://pan.xunlei.com/s/VO90S55J1LXV4IvAhqyC5MGPA1?pwd=586a#' },
    { text: 'ArcGIS Pro 3.4', url: 'https://pan.xunlei.com/s/VOLMeb1QapvscF64rsOCssFjA1?pwd=5vyg#' },
    { text: 'ArcGIS 2023', url: 'https://pan.xunlei.com/s/VO90SbL-6NsbFcZIibQBvkAWA1?pwd=9e9b#' },
    { text: 'ArcGIS 10.8.2', url: 'https://pan.xunlei.com/s/VOMI2zc_bPKRgkKbs1UIPE96A1?pwd=zzpd#' },
    { text: 'ArcGIS 10.8', url: 'https://pan.xunlei.com/s/VO90SKBGzObzLO4mndSZ8tZpA1?pwd=y6g5#' },
    { text: 'Enscape 4.5', url: 'https://pan.xunlei.com/s/VOMq0QZzbjNuQ1O46mdOPfcGA1?pwd=yi3p#' },
    { text: 'Enscape 4.4', url: 'https://pan.xunlei.com/s/VOL4IsEmJcZHWa6U2vPFC-NiA1?pwd=eu8b#' },
    { text: 'Enscape 4.2', url: 'https://pan.xunlei.com/s/VOCCP_g5syD3rrYdkms00GmLA1?pwd=iby7#' },
    { text: 'Enscape 4.1', url: 'https://pan.xunlei.com/s/VNzGomnHwoZJxhvQRI5LD3lDA1?pwd=wq8a#' },
    { text: 'Enscape 3.56', url: 'https://pan.xunlei.com/s/VNrPC7O4YZ4JcJVfOWpl50LKA1?pwd=czet#' },
    { text: 'Enscape 3.4', url: 'https://pan.xunlei.com/s/VNrPCQ4OjahERweBq7bvvfKiA1?pwd=2786#' },
    { text: 'Enscape 3.3', url: 'https://pan.xunlei.com/s/VNrPC_zRfKxh4k0KGYtrqeU0A1?pwd=rkkz#' },
    { text: 'Enscape 3.0', url: 'https://pan.xunlei.com/s/VNrPCfg62xJI7X3S1VqPwJynA1?pwd=7n4h#' },
    { text: 'ZBrush 2025', url: 'https://pan.xunlei.com/s/VO90UBv0PMPUswd9T1Lp3vaRA1?pwd=ecs4#' },
    { text: 'ZBrush 2024', url: 'https://pan.xunlei.com/s/VNrPDF7vYoQuYhIBB28pvUKjA1?pwd=2nxe#' },
    { text: 'ZBrush 2023', url: 'https://pan.xunlei.com/s/VNrPDIzp8QK2Hk6SnMWoxToBA1?pwd=3gnx#' },
    { text: 'ZBrush 2022', url: 'https://pan.xunlei.com/s/VNrPDNFJ2v1gox_A1sDjXrGoA1?pwd=zqpt#' },
    { text: 'ZBrush 2021', url: 'https://pan.xunlei.com/s/VNrPDRiV9C96niRJvpJgXn64A1?pwd=32p3#' },
    { text: 'ZBrush 2020', url: 'https://pan.xunlei.com/s/VNrPDU33mKHZd4RHTjKuHbLlA1?pwd=vgnj#' },
    { text: 'ZBrush 2019', url: 'https://pan.xunlei.com/s/VNrPDZgua7GZUUXagnCmTpGIA1?pwd=zxdk#' },
    { text: 'ZBrush 2018', url: 'https://pan.xunlei.com/s/VNrPDcvJjahERweBq7bvw088A1?pwd=3ens#' },
    { text: 'Lumion 2024', url: 'https://pan.xunlei.com/s/VOF7f7YQcxaH22UKQAZmJU35A1?pwd=98jh#' },
    { text: 'Lumion 2023', url: 'https://pan.xunlei.com/s/VODvL44hF5BifgX0XfWTeNeTA1?pwd=s3wy#' },
    { text: 'Lumion 12', url: 'https://pan.xunlei.com/s/VNrPvSnYmpAYQ1a_o4LuKJiHA1?pwd=ttzk#' },
    { text: 'Lumion 11', url: 'https://pan.xunlei.com/s/VNrPvhDphuInkXXJaJAtXRyiA1?pwd=cdj8#' },
    { text: 'Lumion 10', url: 'https://pan.xunlei.com/s/VNrPvlwwVNHPZYmCh-mALuglA1?pwd=5dqn#' },
    { text: 'Lumion 9', url: 'https://pan.xunlei.com/s/VNrPvrTC8_RkqS-lqRkbANMlA1?pwd=zdsf#' },
    { text: 'Lumion 8', url: 'https://pan.xunlei.com/s/VNrPvvt6_uKgg9hkzwApsgeiA1?pwd=8unz#' },
    { text: 'KeyShot 2025', url: 'https://pan.xunlei.com/s/VOLTVX2laKeUkHtMlA8-KbG-A1?pwd=y24a#' },
    { text: 'KeyShot 2024.3', url: 'https://pan.xunlei.com/s/VOAqdU6WkvW6xePIesnuSBdeA1?pwd=gxsj#' },
    { text: 'KeyShot 2024', url: 'https://pan.xunlei.com/s/VNxSwy1s4CeFJ2mTzqtry2fpA1?pwd=n8d2#' },
    { text: 'KeyShot 2023', url: 'https://pan.xunlei.com/s/VNrPyUsDhuInkXXJaJAtY8LAA1?pwd=ujv3#' },
    { text: 'KeyShot 11', url: 'https://pan.xunlei.com/s/VNrPyfleiSr7iBYEmqA1vXh3A1?pwd=6x8v#' },
    { text: 'KeyShot 10', url: 'https://pan.xunlei.com/s/VNrPykVa_RA9VonWD8U_OmEpA1?pwd=xfdg#' },
    { text: 'KeyShot 9', url: 'https://pan.xunlei.com/s/VNrPyomFTqRPQiWBSmGX3nGmA1?pwd=qsy5#' },
    { text: 'KeyShot 8', url: 'https://pan.xunlei.com/s/VNrPyt428QK2Hk6SnMWp8HxPA1?pwd=m3g6#' },
    { text: 'KeyShot 7', url: 'https://pan.xunlei.com/s/VNrPyxH18QK2Hk6SnMWp8IhpA1?pwd=jzcc#' },
    { text: 'ENVI 5.6', url: 'https://pan.xunlei.com/s/VNrhZk-WXJedx9CfFnXWgLXRA1?pwd=ig7u#' },
    { text: 'Protel 99SE', url: 'https://pan.quark.cn/s/8e2a6cda4a7f' },
    { text: 'multisim 14.3', url: 'https://pan.xunlei.com/s/VNqaSmB9V5tOoEsI5Z5h9eccA1?pwd=zbpp#' },
    { text: 'multisim 14.2', url: 'https://pan.quark.cn/s/0a3a71caef02' },
    { text: 'multisim 14.0', url: 'https://pan.xunlei.com/s/VNqaStcHFJ9XqL05KHqPrdT5A1?pwd=ty6r#' },
    { text: 'multisim 13.0', url: 'https://pan.xunlei.com/s/VNqaSydCD1pVjHF1OvdpnXWOA1?pwd=nu2t#' },
    { text: 'multisim 12.0', url: 'https://pan.xunlei.com/s/VNqaT1yHM5pQALTqwjHQI486A1?pwd=75m5#' },
    { text: 'ansys 2025', url: 'https://pan.xunlei.com/s/VOF7o9TdZkS-1pza-kQAq48lA1?pwd=qg39#' },
    { text: 'ansys 2024', url: 'https://pan.xunlei.com/s/VNudkj9ozxCVmPlfOOZ7YUmWA1?pwd=ftbr#' },
    { text: 'ansys 2023', url: 'https://pan.xunlei.com/s/VNo6KSVQwYPUTOXGEbjUwm38A1?pwd=pjmd' },
    { text: 'ansys 2022', url: 'https://pan.xunlei.com/s/VNo6KZK3jLWq4F3YV8zKE3-dA1?pwd=ipnd' },
    { text: 'ansys 2021', url: 'https://pan.xunlei.com/s/VNo6Kcw0890L2P7eCUhh7euOA1?pwd=7w8f' },
    { text: 'ansys 2020', url: 'https://pan.xunlei.com/s/VNo6KizGzCViEQ2O8_o7h0NHA1?pwd=f7jj' },
    { text: 'ansys 2019', url: 'https://pan.xunlei.com/s/VNo6KtQn9FzZf47CBthDozdGA1?pwd=9w2d' },
    { text: 'Ansys Zemax OpticStudio 2024', url: 'https://pan.xunlei.com/s/VNxaEtqZCwVvpN9hWlJgZh22A1?pwd=3rbu#' },
    { text: 'Ansys Zemax OpticStudio 2023', url: 'https://pan.xunlei.com/s/VNxaF3lLgXkn-5i91GhYVYEdA1?pwd=8yxw#' },
    { text: 'Ansys Zemax OpticStudio 2022', url: 'https://pan.xunlei.com/s/VNxaF7uu3tsu5hnxUZg0PN6-A1?pwd=pcu7#' },
    { text: 'Ansys Electronics 2024', url: 'https://pan.xunlei.com/s/VNxadH4FSY_B7xrd57yUMI7vA1?pwd=t9pt#' },
    { text: 'Ansys Electronics 2023', url: 'https://pan.xunlei.com/s/VNxadt-K4CeFJ2mTzqtuVAyNA1?pwd=5u6e#' },
    { text: 'Ansys Electronics 2022', url: 'https://pan.xunlei.com/s/VNxady5kl-OxNvW5Pu7YTGzLA1?pwd=6fz4#' },
    { text: 'Ansys Electronics 2021', url: 'https://pan.xunlei.com/s/VNxae22Z3tsu5hnxUZg0W0xvA1?pwd=ayb2#' },
    { text: 'EPLAN Electric 2024', url: 'https://pan.xunlei.com/s/VNv2qq6KILtkqXQYuqYI5mz1A1?pwd=g4e3#' },
    { text: 'EPLAN Electric 2023', url: 'https://pan.xunlei.com/s/VNv30USCQZrfhGgUQE90rpU9A1?pwd=dzc4#' },
    { text: 'EPLAN Electric 2022', url: 'https://pan.xunlei.com/s/VNv30YJrViPDZJnmTOwAoCAtA1?pwd=f7i9#' },
    { text: 'EPLAN Electric 2.9', url: 'https://pan.xunlei.com/s/VOCgtHFIJy4aZzM48T23sGowA1?pwd=my6c#' },
    { text: 'Proteus 8.17 SP4', url: 'https://pan.xunlei.com/s/VOKGyyrChY1ntjGryZz71wNVA1?pwd=3u3n#' },
    { text: 'Proteus 8.17', url: 'https://pan.xunlei.com/s/VNv30jHgrRwqqxbivr4ZZ0jiA1?pwd=5kj9#' },
    { text: 'Proteus 8.15', url: 'https://pan.xunlei.com/s/VNqaBiMjyqSl9wV3Bcf8hlbQA1?pwd=suxb#' },
    { text: 'Proteus 8.13', url: 'https://pan.xunlei.com/s/VNqaTMq4E80w4758XWmeTu3lA1?pwd=49ec#' },
    { text: 'Proteus 8.9', url: 'https://pan.xunlei.com/s/VNqaTRdSBKWiTLFbgJeW0I5BA1?pwd=s838#' },
    { text: 'Proteus 8.6', url: 'https://pan.xunlei.com/s/VNqaTW2RzZt9sWTk5Ibf2U7WA1?pwd=q7zf#' },
    { text: 'Proteus 7.8', url: 'https://pan.xunlei.com/s/VNqaTZNWZuqojpPY2chr340zA1?pwd=gwu5#' },
    { text: 'Altium Designer 25.2', url: 'https://pan.xunlei.com/s/VOOuYP5tnO0d26FnN5uT3_k1A1?pwd=brsm#' },
    { text: 'Altium Designer 25.0', url: 'https://pan.xunlei.com/s/VOCCQ0yaIYvGhKbNGYhPP2MhA1?pwd=hxms#' },
    { text: 'Altium Designer 24.0', url: 'https://pan.xunlei.com/s/VNqaCWQOINZqXatF5l3E-hMVA1?pwd=ay25#' },
    { text: 'Altium Designer 23.0', url: 'https://pan.xunlei.com/s/VNv308kGzsZgpJlVUgAgOMJ3A1?pwd=c4vg#' },
    { text: 'Altium Designer 22.0', url: 'https://pan.xunlei.com/s/VNv30CH8fn3P_O21nvCsyde8A1?pwd=884e#' },
    { text: 'Altium Designer 21.0', url: 'https://pan.xunlei.com/s/VNv30FgCxliNst19L1IRCx3-A1?pwd=9bft#' },
    { text: 'Altium Designer 20.0', url: 'https://pan.xunlei.com/s/VNv30JMf4wHIpQXU-PaQ5ReOA1?pwd=9csp#' },
    { text: 'Altium Designer 19.0', url: 'https://pan.xunlei.com/s/VNv30Nnf6PXH7aJ35c7OzNs5A1?pwd=qcxz#' },
    { text: 'TIA（博途）Portal V19', url: 'https://pan.xunlei.com/s/VNx3JjSsO9mUA9ZLNcjOn_iiA1?pwd=nfcd#' },
    { text: 'TIA（博途）Portal V18', url: 'https://pan.xunlei.com/s/VNx3JmUNC5hipr1kfg5EZQI7A1?pwd=uvet#' },
    { text: 'TIA（博途）Portal V17', url: 'https://pan.xunlei.com/s/VNx3Jpkrf_ucQU3ZHFA-W7QWA1?pwd=wzta#' },
    { text: 'TIA（博途）Portal V16', url: 'https://pan.xunlei.com/s/VNzzsOb23JZM0I7x1ceCYAUSA1?pwd=emt9#' },
    { text: 'TIA（博途）Portal V15', url: 'https://pan.xunlei.com/s/VNx3JyYJKXgHTGPn-FZ2792-A1?pwd=ki4h#' },
    { text: 'COMSOL 6.3', url: 'https://pan.xunlei.com/s/VOEO8I3EZ_r2fChc4AawkihyA1?pwd=xh6q#' },
    { text: 'COMSOL 6.2', url: 'https://pan.xunlei.com/s/VNrPAk69x66gQ27KFsgcQz7TA1?pwd=x6pj#' },
    { text: 'COMSOL 6.0', url: 'https://pan.xunlei.com/s/VNrPAcK-MNpBBllToro9CZPkA1?pwd=nb9k#' },
    { text: 'Quartus II 18', url: 'https://pan.xunlei.com/s/VNrhYllDMhkQma3-AfPuJy_cA1?pwd=5jvp#' },
    { text: 'VRay 6.2 for 3ds Max2019- 2024', url: 'https://pan.quark.cn/s/d3dc5d2ce9dd' },
    { text: 'VRay 6.1 for 3ds Max2019- 2024', url: 'https://pan.quark.cn/s/a68d4a24dbe6' },
    { text: 'VRay 6.0 for 3ds Max2019- 2024', url: 'https://pan.quark.cn/s/dfa6bce7bbbc' },
    { text: 'VRay 5.2 for 3ds Max2019- 2022', url: 'https://pan.quark.cn/s/e9f2b2b31010' },
    { text: 'VRay 5.1 for 3ds Max2019- 2022', url: 'https://pan.quark.cn/s/fd1f83772fac' },
    { text: 'VRay 4.3 for 3ds Max 2020', url: 'https://pan.quark.cn/s/cd7bc1d68d2f' },
    { text: 'VRay 4.1 for 3ds Max2013-2019', url: 'https://pan.quark.cn/s/69f5fd476080' },
    { text: 'VRay 6.1 for SketchUp2019-2023', url: 'https://pan.quark.cn/s/e5fd5aee64d5' },
    { text: 'VRay 6.0 for SketchUp2019-2022', url: 'https://pan.quark.cn/s/42d79fef4580' },
    { text: 'VRay 5.2 for SketchUp2019-2022', url: 'https://pan.quark.cn/s/e90dccca00ce' },
    { text: 'VRay 5.1 for SketchUp2017-2021', url: 'https://pan.quark.cn/s/8eeb3a630558' },
    { text: 'VRay 4.2 for SketchUp2016-2020', url: 'https://pan.quark.cn/s/04af289063f4' },
    { text: 'VRay 4.1 for SketchUp2016-2019', url: 'https://pan.quark.cn/s/4b1085171577' },
    { text: 'VRay 6.0 for Rhino6-8', url: 'https://pan.quark.cn/s/c790ee662fcc' },
    { text: 'VRay 5.2 for Rhino6-8', url: 'https://pan.quark.cn/s/5bbe14f136a6' },
    { text: 'VRay 5.1 for Rhino6-7', url: 'https://pan.quark.cn/s/9a23ecc2d9d4' },
    { text: 'VRay 4.2 for Rhino5-7', url: 'https://pan.quark.cn/s/6abf93406bf7' },
    { text: 'VRay 4.1 for Rhino5-6', url: 'https://pan.quark.cn/s/39aa5f762776' },
    { text: 'IMD安装包及激活工具', url: 'https://pan.xunlei.com/s/VNvN_JfO9P-CiJX9JiixfDsBA1?pwd=3t73#' },
    { text: '安卓游戏百宝箱1', url: 'https://pan.quark.cn/s/6a6d42356259' },
    { text: '安卓游戏百宝箱2', url: 'https://pan.xunlei.com/s/VNvSTXjGSVk4-5IzlmZGeyhFA1?pwd=x2af#' },
    { text: 'PC游戏百宝箱1', url: 'https://pan.quark.cn/s/397b80564caa' },
    { text: 'PC游戏百宝箱2', url: 'https://pan.xunlei.com/s/VNvST_mVrorVMQkfMUG739jEA1?pwd=sbrz#' },
    { text: '免费电视TV盒子软件百宝箱', url: 'https://pan.quark.cn/s/11e3aba5c6e0' },
    { text: 'Rhino 8.13', url: 'https://pan.xunlei.com/s/VOCfatOmK27HvOWEEKOi1PLCA1?pwd=u9ie#' },
    { text: 'Rhino 8.12', url: 'https://pan.xunlei.com/s/VO90TBGoQunnpl1aLvNCW60dA1?pwd=w2nt#' },
    { text: 'Rhino 8.9', url: 'https://pan.xunlei.com/s/VO2e8jgZ0sA_Jkmblm3wzh7kA1?pwd=spkd#' },
    { text: 'Rhino 8.6', url: 'https://pan.xunlei.com/s/VNvbiDt361wKUxMIPpGu80M1A1?pwd=zabp#' },
    { text: '剪映国际版（Mac版）', url: 'https://pan.xunlei.com/s/VNy6ma8_8Wp5qjj118f8og2-A1?pwd=yivb#' },
    { text: '剪映国际版（Win版）', url: 'https://pan.xunlei.com/s/VNy6mfpkad5Z1gEgyF4WzU8nA1?pwd=34f2#' },
    { text: '剪映手机版', url: 'https://pan.quark.cn/s/289917b28751' },
    { text: '剪映window版本', url: 'https://pan.xunlei.com/s/VO4AA5rlZCefPN6zrSqztrJHA1?pwd=smej#' },
    { text: '视频搬运工具', url: 'https://pan.quark.cn/s/987b67ee1eb1' },
    { text: '闪豆下载器', url: 'https://pan.xunlei.com/s/VNvrMebsUUrvGA33TFCVS5bNA1?pwd=kwr4#' },
    { text: 'B站下载工具', url: 'https://pan.xunlei.com/s/VNvrN3c4FC1b_IjfHu_NC1fQA1?pwd=fbs9#' },
    { text: '网易云音乐', url: 'https://pan.quark.cn/s/90f04c2caf13' },
    { text: 'SAS 9.4', url: 'https://pan.xunlei.com/s/VNwTxWpu8pjIrKfO8qcfKBwQA1?pwd=75r9#' },
    { text: 'WinRAR', url: 'https://pan.xunlei.com/s/VOCfbjEQevaTGDLXA-LGN7C_A1?pwd=t4id#' },
    { text: 'Solid Edge 2025', url: 'https://pan.xunlei.com/s/VOCfd2XbevaTGDLXA-LGNXV6A1?pwd=jatj#' },
    { text: 'Solid Edge 2024', url: 'https://pan.xunlei.com/s/VOCfd4TfQujy-dhM3WTUQEzEA1?pwd=zin4#' },
    { text: 'MathType 7.7', url: 'https://pan.xunlei.com/s/VOK1UzNM4vkKZN3Iz-0zjgvGA1?pwd=xv5n#' },
    { text: 'MathType 7.4', url: 'https://pan.xunlei.com/s/VOK1V1dp4vkKZN3Iz-0zjiqpA1?pwd=kdrh#' },
    { text: 'MathType 6.9', url: 'https://pan.xunlei.com/s/VOK1V3wx4vkKZN3Iz-0zjkBMA1?pwd=n78w#' },
    { text: '酷我音乐', url: 'https://pan.quark.cn/s/573df4272fb1' },
    { text: '落雪音乐', url: 'https://pan.quark.cn/s/4a96be766f31' },
    { text: '方格音乐', url: 'https://pan.quark.cn/s/f2e9faabb65c' },
    { text: 'radishes音乐', url: 'https://pan.quark.cn/s/bd017bc35dc9' },
    { text: '全能DLL修复工具', url: 'https://pan.quark.cn/s/b2c0b48e7d21' },
    { text: '酷狗音乐', url: 'https://pan.quark.cn/s/4708056cdb64' },
    { text: '动漫软件集合', url: 'https://pan.quark.cn/s/1113addca732' },
    { text: '漫画软件集合', url: 'https://pan.quark.cn/s/66c416695e03' },
    { text: '追剧软件集合', url: 'https://pan.quark.cn/s/9b08d5856a0c' },
    { text: '听书软件集合', url: 'https://pan.quark.cn/s/e4d38a5f5000' },
    { text: '听歌软件集合', url: 'https://pan.quark.cn/s/200469b50901' },
    { text: '小说软件集合', url: 'https://pan.quark.cn/s/0d8c339743ab' },
    // { text: 'ae 插件一键安装板', url: 'https://pan.xunlei.com/s/VNwm9sGrJT_pZFofzXexn5axA1?pwd=yzdh#' },
    // { text: 'lr 插件一键安装板', url: 'https://pan.xunlei.com/s/VNwmARhDTtgXbN_AGPEKRlvXA1?pwd=9kxb#' },
    // { text: 'C4D 插件一键安装板', url: 'https://pan.xunlei.com/s/VNwmBJDTCmZoV5LwnWBgn1adA1?pwd=kgb3#' },
    { text: 'Topaz photo AI v3.0.3(Mac版)', url: 'https://pan.xunlei.com/s/VO-eg2mhgAWARMpcA4d27P6_A1?pwd=utk8#' },
    { text: 'Topaz Photo AI 3.0.5', url: 'https://pan.xunlei.com/s/VO-eg95UEMsTiBBOPY2HyF8tA1?pwd=svrb#' },
    { text: 'Topaz Photo AI 3.0.4', url: 'https://pan.xunlei.com/s/VO-eg5k4fPQzccT1Fqb_fUDwA1?pwd=7tsm#' },
    { text: 'Topaz Photo AI 3.0.1', url: 'https://pan.xunlei.com/s/VO-ehFEWIYaptktIfMB0IIQIA1?pwd=2t2a#' },
    { text: 'Topaz Photo AI 2.4.2', url: 'https://pan.xunlei.com/s/VNxVVaeXWgjcEBRZIODDY9IPA1?pwd=z4gs#' },
    { text: 'Topaz Adjust AI 1.0.6', url: 'https://pan.xunlei.com/s/VNxVX2P_WgjcEBRZIODDYY63A1?pwd=zxsr#' },
    { text: 'Topaz DeNoise AI 3.7.2', url: 'https://pan.xunlei.com/s/VNxVXlDBFM4UO5WuF-sTuap2A1?pwd=geiq#' },
    { text: 'Topaz Gigapixel AI(mac版本)', url: 'https://pan.xunlei.com/s/VO07qkbotYpoNAYFr5Cm5m3GA1?pwd=jacc#' },
    { text: 'Topaz Gigapixel AI 7.2.1', url: 'https://pan.xunlei.com/s/VO07qa1sobm28fRrB9GnkURxA1?pwd=f8v8#' },
    { text: 'Topaz Gigapixel AI 7.1.2', url: 'https://pan.xunlei.com/s/VO-ehOcIz14CeDxn1H5ZXf66A1?pwd=c569#' },
    { text: 'Topaz Gigapixel AI 7.1.0', url: 'https://pan.xunlei.com/s/VNxVYa2VKZqhBspmP5_IOjqxA1?pwd=gwu6#' },
    { text: 'Topaz JPEG to RAW AI 2.2.1', url: 'https://pan.xunlei.com/s/VNxVZ43aWgjcEBRZIODDZ9FSA1?pwd=mk7w#' },
    { text: 'Topaz Mask AI 1.3.9', url: 'https://pan.xunlei.com/s/VNxV_l4_pWoyvgSCJlJGVWXnA1?pwd=4ec3#' },
    { text: 'Topaz Sharpen AI 4.1.0', url: 'https://pan.xunlei.com/s/VNxVaLgTjE3V6l_36sReCZKmA1?pwd=xfta#' },
    { text: 'Topaz Studio AI 2.3.2', url: 'https://pan.xunlei.com/s/VNxW2PA0GeRr3iB2bLHnqWegA1?pwd=qa99#' },
    { text: 'Topaz Video AI v5.1.4(MAC版)', url: 'https://pan.xunlei.com/s/VO0X50Lf2IYHO2Y7urydAFTjA1?pwd=sj5y#' },
    { text: 'Topaz Video AI v5.1.4', url: 'https://pan.xunlei.com/s/VO0X4pda2Nsv_IiIV-PUnPYaA1?pwd=qwu7#' },
    { text: 'Topaz Video AI 4.0.6', url: 'https://pan.xunlei.com/s/VNxW2vZjKTjGa32qu8dkELanA1?pwd=wqbg#' },
    { text: 'ArtCAM 2018', url: 'https://pan.xunlei.com/s/VNx_jm0URNhXxLcGKLaBBtWSA1?pwd=gs27#' },
    { text: 'ArtCAM 2017', url: 'https://pan.xunlei.com/s/VNx_nTNdKZqhBspmP5_JzXwiA1?pwd=y2ki#' },
    { text: 'Mudbox 2024', url: 'https://pan.xunlei.com/s/VNxaF_mCpB3_y6iMtenGZwevA1?pwd=qm2f#' },
    { text: 'Mudbox 2023', url: 'https://pan.xunlei.com/s/VNxaGahu5GrjCPG2w1g4ku_gA1?pwd=zsag#' },
    { text: 'Mudbox 2022', url: 'https://pan.xunlei.com/s/VNxaGgFxLdQmnJPCWSMesU_kA1?pwd=a763#' },
    { text: 'Vero visi 2023', url: 'https://pan.xunlei.com/s/VNxaMZnv_vvcl4W0VhGSzw2bA1?pwd=zfp7#' },
    { text: 'Vero visi 2021', url: 'https://pan.xunlei.com/s/VNxaMcOKEHCoFAZRPn2NUasxA1?pwd=vtmq#' },
    { text: 'Midas Civil 2022', url: 'https://pan.xunlei.com/s/VNxzRlcUAODqR8S93dm77lbYA1?pwd=e764#' },
    { text: 'Midas Civil 2019', url: 'https://pan.xunlei.com/s/VNxaLXuxpyNnDgly1ZjkX3j4A1?pwd=4rzx#' },
    { text: 'Midas Civil 2017', url: 'https://pan.xunlei.com/s/VNxaLbJZpWQJlyyxouCDLCSnA1?pwd=4tme#' },
    { text: 'Mathematica 14', url: 'https://pan.xunlei.com/s/VNx_aHWurJftHx7M2BfU1CHBA1?pwd=bi59#' },
    { text: 'Mathematica 13', url: 'https://pan.xunlei.com/s/VNx_aN5hpyNnDgly1ZjkLE7DA1?pwd=kumq#' },
    { text: 'Mathematica 12', url: 'https://pan.xunlei.com/s/VNx_aRYIW3-UtX5wQN7IxiP_A1?pwd=48hu#' },
    { text: 'Tableau 2023', url: 'https://pan.xunlei.com/s/VNx_beC0pWoyvgSCJlJI4OPiA1?pwd=z3a4#' },
    { text: 'Tableau 2021', url: 'https://pan.xunlei.com/s/VNx_bivSRNhXxLcGKLaBALSXA1?pwd=ipke#' },
    { text: 'Lingo 18', url: 'https://pan.xunlei.com/s/VNx_cNQ-pB3_y6iMtenGPsiaA1?pwd=kp7j#' },
    { text: 'Lingo 17', url: 'https://pan.xunlei.com/s/VNx_cSGyQSJqr2XEMY50cUfVA1?pwd=cih2#' },
    { text: 'Lingo 12', url: 'https://pan.xunlei.com/s/VNx_cXqVnq527-nfzCeNviSvA1?pwd=dkue#' },
    { text: 'Lingo 11', url: 'https://pan.xunlei.com/s/VNx_capDpWoyvgSCJlJI4_L6A1?pwd=hcj7#' },
    { text: 'Substance 3D 2024', url: 'https://pan.xunlei.com/s/VNx_f1B0gXkn-5i91GhYMNRNA1?pwd=ak5b#' },
    { text: 'Substance 3D 2023', url: 'https://pan.xunlei.com/s/VNx_gWBepWoyvgSCJlJI5YnEA1?pwd=jq7t#' },
    { text: 'Substance 3D 2022', url: 'https://pan.xunlei.com/s/VNx_g_J7TDq9akJoUWoV9wyvA1?pwd=erbf#' },
    { text: 'Substance 3D 2021', url: 'https://pan.xunlei.com/s/VNx_gccwIf2Y6cHuaquiUuTPA1?pwd=sni9#' },
    { text: 'CorelCAD 2023', url: 'https://pan.xunlei.com/s/VNx_jm0URNhXxLcGKLaBBtWSA1?pwd=gs27#' },
    { text: 'CorelCAD 2021', url: 'https://pan.xunlei.com/s/VNx_jpsA0A3R7MVgLUeDFeyIA1?pwd=gz2w#' },
    { text: 'Proe 5.0M280', url: 'https://pan.xunlei.com/s/VNx_loCPm4pwo5OfC585x4ZjA1?pwd=fwsy#' },
    { text: 'Proe 5', url: 'https://pan.xunlei.com/s/VNx_luOPKTjGa32qu8dldnnNA1?pwd=2cah#' },
    { text: 'Dynaform 5.9.4', url: 'https://pan.xunlei.com/s/VNxaH9XuSbdxYVEtRHN8toWgA1?pwd=qqkf#' },
    { text: 'VMware 17.6.3', url: 'https://pan.xunlei.com/s/VOL4IVCKK3Cqm0JC4DjsSOshA1?pwd=q34t#' },
    { text: 'VMware 17.6', url: 'https://pan.xunlei.com/s/VO90TuZuLH9GKEGxvU0Q8gABA1?pwd=tjpq#' },
    { text: 'VMware 17.5', url: 'https://pan.xunlei.com/s/VNxcbQTUnDaqCJcnuKqTolJ_A1?pwd=amje#' },
    { text: 'VMware 16', url: 'https://pan.xunlei.com/s/VO6v8I3-UQrUwnMjzp2LirAiA1?pwd=e8ei#' },
    { text: '直接安装Win7', url: 'https://pan.xunlei.com/s/VNxkexfl72Z_Dlpg6rP2WELOA1?pwd=cz76#' },
    { text: 'U盘安装Win7', url: 'https://pan.xunlei.com/s/VNxkf-shLUQAkrwW2BhTsMlSA1?pwd=7t4h#' },
    { text: '虚拟机装Win7', url: 'https://pan.xunlei.com/s/VNxkf2WL0CAFtaVXcWLShp2vA1?pwd=9cn8#' },
    { text: '直接安装Win10', url: 'https://pan.xunlei.com/s/VNxkfHNPKOCW-4tz0equNNdJA1?pwd=33a2#' },
    { text: 'U盘安装Win10', url: 'https://pan.xunlei.com/s/VNxkfKE63o7MZYRUP46q30vEA1?pwd=ss65#' },
    { text: '虚拟机装Win10', url: 'https://pan.xunlei.com/s/VNxkfNVuqFEawj89PEBzFclkA1?pwd=dstc#' },
    { text: '直接安装Win11', url: 'https://pan.xunlei.com/s/VNyfbjXAzCHzD-TFi4K9ylEYA1?pwd=2py9#' },
    { text: 'U盘安装Win11', url: 'https://pan.xunlei.com/s/VNxkfpdise99dfcjtOUFepmsA1?pwd=awv5#' },
    { text: '虚拟机装Win11', url: 'https://pan.xunlei.com/s/VNxkfnTJse99dfcjtOUFepHDA1?pwd=i5fj#' },
    { text: '卸载工具geek', url: 'https://pan.quark.cn/s/a3110760f22b' },
    { text: '虚拟光驱', url: 'https://pan.xunlei.com/s/VNygFkDkS4T29bpo0k8yvfViA1?pwd=xs3k#' },
    { text: 'QuickLook + Seer', url: 'https://pan.xunlei.com/s/VNywvlyi7bKVoLo6nKqsYHSJA1?pwd=fb2h#' },
    { text: 'EasyDrv 8（VIP版）', url: 'https://pan.xunlei.com/s/VNzGkPRYyYUnN2Iw-v8319rBA1?pwd=rcih#' },
    { text: 'LaTex 2025', url: 'https://pan.xunlei.com/s/VOLyr_7lsfFFj2p4g8eksY9pA1?pwd=kzpv#' },
    { text: 'LaTex 2024', url: 'https://pan.xunlei.com/s/VO4Qe_HWC1XHZpR5h5HGwhSyA1?pwd=83dv#' },
    { text: 'Luminar Neo(mac版本)', url: 'https://pan.xunlei.com/s/VO0XBzTUjc7kuo1VODiP288EA1?pwd=gdtn#' },
    { text: 'Luminar Neo 1.20', url: 'https://pan.xunlei.com/s/VO0X7osDj8KphooNsenINkEYA1?pwd=dnqv#' },
    { text: 'Luminar Neo 1.19', url: 'https://pan.xunlei.com/s/VO0X7uGXBPYfXw2Rn2qDCW8XA1?pwd=5ia8#' },
    { text: '斯沃7.2', url: 'https://pan.xunlei.com/s/VO3lGQVbQtt4ZKDiZKFuYaV3A1?pwd=b22u#' },
    { text: '西门子模拟器', url: 'https://pan.xunlei.com/s/VO0X7uGXBPYfXw2Rn2qDCW8XA1?pwd=5ia8#' },
    { text: '新代五轴模拟器', url: 'https://pan.xunlei.com/s/VO3lFuPT876BnrR5fGJb7rlAA1?pwd=ju6y#' },
    { text: '新代车铣复合模拟器', url: 'https://pan.xunlei.com/s/VO3lG-M1uie0UQdkoYDW5xn6A1?pwd=x425#' },
    { text: '海德汉530模拟器', url: 'https://pan.xunlei.com/s/VO3lGCZPUgRJ9bhAhcYYNpwDA1?pwd=kzvb#' },
    { text: 'Vero VISI 2023', url: 'https://pan.xunlei.com/s/VO45uljTDzFSHHjERwv9q8upA1?pwd=et43#' },
    { text: 'Vero VISI 2021', url: 'https://pan.xunlei.com/s/VO45uoWJkqCqoKeJplBBKYmnA1?pwd=wast#' },
    { text: 'Vero VISI 2020', url: 'https://pan.xunlei.com/s/VO45uqcoFzpYYdvljdTjCRkfA1?pwd=4ch6#' },
    { text: 'CIMCO Edit 2025', url: 'https://pan.xunlei.com/s/VOODjiyIqG6L0nhLfFkaqo7tA1?pwd=m6u3#' },
    { text: 'CIMCO Edit 2024', url: 'https://pan.xunlei.com/s/VO45wMWL7dCpNMETKTldhFL2A1?pwd=8dga#' },
    { text: 'CIMCO Edit 2023', url: 'https://pan.xunlei.com/s/VO45wOmad8AMSfKyHbYpxjrGA1?pwd=3nf4#' },
    { text: 'CIMCO Edit 2022', url: 'https://pan.xunlei.com/s/VO45wRABs4NPoRE_ol4zKp77A1?pwd=cgp9#' },
    { text: 'EndNote 2025', url: 'https://pan.xunlei.com/s/VOOwt88vOZ7sHno8EpjFUHiAA1?pwd=73cc#' },
    { text: 'EndNote 21.5', url: 'https://pan.xunlei.com/s/VOCJTgGxvHb0be1H8lAAykyNA1?pwd=n59g#' },
    { text: 'EndNote 21.4', url: 'https://pan.xunlei.com/s/VO4QkFgb5PgyoT6OPXd1u1DSA1?pwd=e8br#' },
    { text: 'EndNote X9', url: 'https://pan.xunlei.com/s/VOCYYQitV4ytDNzMKk-YR_qxA1?pwd=w8by#' },
    { text: 'AxMath 2.6', url: 'https://pan.xunlei.com/s/VO60KPRHB12AhPCXnahhiLJlA1?pwd=jk3s#' },
    { text: 'Xmanager 8', url: 'https://pan.xunlei.com/s/VO90Xvj8Qunnpl1aLvNCZ2RkA1?pwd=maa7#' },
    { text: 'Xshell 8', url: 'https://pan.xunlei.com/s/VO90Xs2h1LXV4IvAhqyC8ug_A1?pwd=ekyj#' },
    { text: 'Xftp 8', url: 'https://pan.xunlei.com/s/VO90XxsMxK0WCFdOPVqK_1r_A1?pwd=et9s#' },
    { text: 'Xlpd 8', url: 'https://pan.xunlei.com/s/VO90Y-4jQBTAPpxRU_Hw_OYcA1?pwd=gndt#' },
    { text: 'Zotero 7.0', url: 'https://pan.xunlei.com/s/VOAM_IB_DuC-2j8_DBZmcKtcA1?pwd=mgyc#' },
    { text: 'NoteExpress 4.0', url: 'https://pan.xunlei.com/s/VOAMaWXMICrxUzpaHu2wa2WTA1?pwd=5grq#' },
    { text: 'CiteSpace 6.3.1', url: 'https://pan.xunlei.com/s/VOAMaqMMGlp1DK-IMhvbS5uqA1?pwd=9678#' },
    { text: '知云文献翻译', url: 'https://pan.xunlei.com/s/VOAMbcQRM4QiVvOwdB3je8O_A1?pwd=juce#' },
    { text: 'CopyTranslator 11.0', url: 'https://pan.xunlei.com/s/VOAMblgPVkokUradGP97b1CJA1?pwd=jaza#' },
    { text: 'Speech to Text for PR2025', url: 'https://pan.xunlei.com/s/VOAMmDpLNkEg_Fq1wRr9SOK-A1?pwd=86m9#' },
    { text: 'Speech to Text for PR2024', url: 'https://pan.xunlei.com/s/VOAMmXUSNkEg_Fq1wRr9SUm-A1?pwd=stkf#' },
    { text: 'Speech to Text for PR2023', url: 'https://pan.xunlei.com/s/VOAMma212kbZy0kO_dQyzCLgA1?pwd=fq4j#' },
    { text: 'Speech to Text for PR2022', url: 'https://pan.xunlei.com/s/VOAMmelkwjqyoyHKf86qAmcEA1?pwd=d2pg#' },
    { text: 'Jade9.0+Findit2017+PDF4-2009', url: 'https://pan.xunlei.com/s/VOEsvsBV0BLswX26HFw2cSpSA1?pwd=hs7k#' },
    { text: 'Jade 9.0', url: 'https://pan.xunlei.com/s/VOEoIrdJVssn7fnYe-Iuj8GjA1?pwd=sfdv#' },
    { text: 'Jade 6.5', url: 'https://pan.xunlei.com/s/VNrhZk-WXJedx9CfFnXWgLXRA1?pwd=ig7u#' },
    { text: 'Sketchpad 5.0.6', url: 'https://pan.xunlei.com/s/VOF7nknEDVW4VmamywnbTcyXA1?pwd=6xgz#' },
    { text: 'window系统和office激活工具', url: 'https://pan.xunlei.com/s/VOFLaZawN7lsZqtqalaWjOB-A1?pwd=iijp#' },

    { text: 'ChemDraw 23.1中文版', url: 'https://pan.xunlei.com/s/VOMfelsc0q7gFIuhj9cCfSkmA1?pwd=emfc#' },
    { text: 'ChemDraw 23', url: 'https://pan.xunlei.com/s/VOIkJGNKieZUx9yH6CNMTS12A1?pwd=i5w2#' },

    { text: 'SPSS 27', url: 'https://pan.xunlei.com/s/VO7mPAviCmHMz6_PesOIyWtWA1?pwd=yavf#' },
    { text: 'SPSS 26', url: 'https://pan.xunlei.com/s/VO7mPGBHYi0ttAtTLYH6a9mLA1?pwd=wif8#' },
    { text: 'SPSS 25', url: 'https://pan.xunlei.com/s/VO7mPDNZYi0ttAtTLYH6a92aA1?pwd=t6kj#' },
    { text: 'SPSS 24', url: 'https://pan.xunlei.com/s/VO7mPJD3PfPHfb-1frJ-KNk9A1?pwd=q6jr#' },
    { text: 'SPSS 23', url: 'https://pan.xunlei.com/s/VO7mPLX5kMiTBWiAWbcOJmiQA1?pwd=dxv8#' },
    { text: 'SPSS 22', url: 'https://pan.xunlei.com/s/VO7mPNkJx0rkPoaEBOfUgnSSA1?pwd=zjmj#' },
    { text: 'SPSS 27', url: 'https://pan.xunlei.com/s/VOAhBjwhQzDSnT2515fgMuRHA1?pwd=f9bp#' },
    { text: 'SPSS 26', url: 'https://pan.xunlei.com/s/VOAhBpU0-7-iZ2UpTeLLf8GXA1?pwd=bwya#' },
    { text: 'SPSS 25', url: 'https://pan.xunlei.com/s/VOAhBsQ63PGiBhN4CQQAHtWfA1?pwd=jfiz#' },
    { text: 'SPSS 24', url: 'https://pan.xunlei.com/s/VOAhBx4Za83B8UJ0t30w2MrtA1?pwd=bmp8#' },
    { text: 'SPSS 23', url: 'https://pan.xunlei.com/s/VOAhBzs3Pkfr8DvmexD6H28NA1?pwd=gtzs#' },
    { text: 'SPSS 22', url: 'https://pan.xunlei.com/s/VOAhC1S3GONOT7lMRvzHX8wtA1?pwd=9hui#' },

    { text: '班迪录屏', url: 'https://pan.xunlei.com/s/VOLMde1bUvgsuKeVgEAgtcYvA1?pwd=8z56#' },

    { text: 'Design Expert 13', url: 'https://pan.xunlei.com/s/VOLN1iRHbM3CqwRo3OucmMxgA1?pwd=8b5c#' },

    { text: 'HyperWorks 2025', url: 'https://pan.xunlei.com/s/VOLN1-trY1NkjZCR6Rwf3maEA1?pwd=y7mb#' },

    { text: 'STAR-CCM+ 2502', url: 'https://pan.xunlei.com/s/VOLN2ZxdtjEWPXt8m0T41EM5A1?pwd=sg2w#' },

    { text: 'CrystalMaker 11.5', url: 'https://pan.xunlei.com/s/VOMeGeXlCH68-ncxsAmMHD0OA1?pwd=bpwt#' },
    { text: '3D Slicer', url: 'https://pan.xunlei.com/s/VOMemUDdb0qlKE8avUD0ZtSjA1?pwd=ykfz#' },
    { text: 'MestReNova 15', url: 'https://pan.xunlei.com/s/VOMenm9Zb2mtUhh9NZyZji0xA1?pwd=7pff#' },
    { text: 'Image-Pro Plus 6.0', url: 'https://pan.xunlei.com/s/VOMeottR-g6JSo2qUpTt3BorA1?pwd=shif#' },
    { text: 'Avantage 6.9', url: 'https://pan.xunlei.com/s/VOMeskBAb0qlKE8avUD0beCEA1?pwd=e84a#' },
    { text: 'RadiAnt DICOM Viewer 2024', url: 'https://pan.xunlei.com/s/VOMeuPgkaW7m0c8zMZZrBd9ZA1?pwd=fg89#' },
    { text: 'RadiAnt DICOM Viewer 2021', url: 'https://pan.xunlei.com/s/VOMeuVU1qvtvLjxKcOVOuWqKA1?pwd=87ma#' },
    { text: 'Diamond 4.6', url: 'https://pan.xunlei.com/s/VOMeyPldrAC3WkmyL6eHDwIpA1?pwd=8rns#' },
    { text: 'Gaussian 16', url: 'https://pan.xunlei.com/s/VOMf-9eB_zRzlnouyqNMtiaCA1?pwd=qweg#' },
    { text: 'ImageJ FIJI', url: 'https://pan.xunlei.com/s/VOMfY_LykiZ6we2MbEEzsLkxA1?pwd=7wif#' },
    { text: 'ImageLab', url: 'https://pan.xunlei.com/s/VOMfZgrRug5eU74JO_R3nGtLA1?pwd=632w#' },
    { text: 'TBtools 1.1', url: 'https://pan.xunlei.com/s/VOMfeTzSAS-lEPQoVoeVwZDLA1?pwd=yx54#' },
    { text: 'Materials Studio 2023', url: 'https://pan.xunlei.com/s/VOMffRca94_I3oQwsr1WNI02A1?pwd=jxtd#' },
    { text: 'CST Studio Suite 2025', url: 'https://pan.xunlei.com/s/VOMfgp46AS-lEPQoVoeVxPWrA1?pwd=tam2#' },
    { text: 'SnapGene 6.0.2', url: 'https://pan.xunlei.com/s/VOMjPiIj94_I3oQwsr1XxbNYA1?pwd=4r7u#' },

    { text: 'CAXA CAM数控车 2025', url: 'https://pan.xunlei.com/s/VOOwnOpjHtixo1UnwyweWV6XA1?pwd=7gvy#' },

    { text: 'Aspen Plus 14.2', url: 'https://pan.xunlei.com/s/VOOwoko3pZRxvQfBcajDcnWCA1?pwd=jj6y#' },

    { text: 'JMatPro 7.0', url: 'https://pan.xunlei.com/s/VOOwr04o7pgJCAYU7Kju0NwAA1?pwd=dnuv#' },

    { text: '浩辰CAD机械版 2025', url: 'https://pan.xunlei.com/s/VOOws11fzNI-UPmlMTHYGFZcA1?pwd=cj2z#' },
    { text: '浩辰CAD机械版 2024', url: 'https://pan.xunlei.com/s/VOOwrya3w9uE1nBZ2V94tSXkA1?pwd=ctff#' },
    { text: '浩辰CAD机械版 2019', url: 'https://pan.xunlei.com/s/VOOwrvaaRLFd38dbpR7BUmfUA1?pwd=7whu#' },

    { text: 'Epidata 4.7', url: 'https://pan.xunlei.com/s/VOOwuAUd-wEAtCmsdBldHxbgA1?pwd=pibr#' },

    { text: 'Tracker 6.3', url: 'https://pan.xunlei.com/s/VOOwviWFDc5hNkYvlj1MdJ2KA1?pwd=jchj#' },

    { text: 'GetDataW 2.26', url: 'https://pan.xunlei.com/s/VOOwxh64czl2IvU-OOiHJXXkA1?pwd=nnjh#' },



    // ... 其他选项
];

searchInput.addEventListener('input', function() {
    const query = this.value.toLowerCase();
    if (query.trim() === '') {
        dropdownMenu.innerHTML = '';
        dropdownMenu.style.display = 'none';
        return;
    }
    const filteredOptions = options.filter(option => option.text.toLowerCase().includes(query)).slice(0, 50); // 最多显示5条
    showDropdown(filteredOptions);
});

function showDropdown(options) {
    dropdownMenu.innerHTML = '';
    if (options.length > 0) {
        dropdownMenu.style.display = 'block';
        options.forEach(option => {
            const a = document.createElement('a');
            a.textContent = option.text;
            a.href = '#';
            a.dataset.url = option.url; // 使用data-url属性存储URL
            a.addEventListener('click', function(e) {
                e.preventDefault(); // 阻止默认的链接跳转行为
                const url = this.dataset.url;
                window.location.href = url; // 跳转到对应的URL
                dropdownMenu.innerHTML = '';
                dropdownMenu.style.display = 'none';
            });
            dropdownMenu.appendChild(a);
        });
    } else {
        dropdownMenu.style.display = 'none';
    }
}